// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class Attribution(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public global::Iskra.StdWeb.AttributionAggregationServices AggregationServices
    {
        get
        {
            global::Iskra.StdWeb.AttributionAggregationServices __res_1718;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_1719 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "aggregationServices");
            __res_1718 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.AttributionAggregationServices>(__res_1719);
            return __res_1718;
        }
    }
}

#nullable disable