// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class AudioBufferSourceNode(global::System.Runtime.InteropServices.JavaScript.JSObject obj): AudioScheduledSourceNode(obj)
{
    public global::Iskra.StdWeb.AudioBuffer? Buffer
    {
        get
        {
            global::Iskra.StdWeb.AudioBuffer? __res_8202;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_8203 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "buffer");
            if (__res_8203 is null)
            {
                __res_8202 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_8204 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_8203;
                __res_8202 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.AudioBuffer>(__notNullable_8204);
            }
            return __res_8202;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_8205;
            if (value is null)
            {
                __marshalledValue_8205 = null;
            }
            else
            {
                global::Iskra.StdWeb.AudioBuffer __notNullable_8206 = (global::Iskra.StdWeb.AudioBuffer)value;
                __marshalledValue_8205 = __notNullable_8206.JSObject;
            }
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "buffer", __marshalledValue_8205);
        }
    }

    public global::Iskra.StdWeb.AudioParam PlaybackRate
    {
        get
        {
            global::Iskra.StdWeb.AudioParam __res_8207;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_8208 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "playbackRate");
            __res_8207 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.AudioParam>(__res_8208);
            return __res_8207;
        }
    }

    public global::Iskra.StdWeb.AudioParam Detune
    {
        get
        {
            global::Iskra.StdWeb.AudioParam __res_8209;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_8210 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "detune");
            __res_8209 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.AudioParam>(__res_8210);
            return __res_8209;
        }
    }

    public bool Loop
    {
        get
        {
            bool __res_8211;
            bool __res_8212 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "loop");
            __res_8211 = __res_8212;
            return __res_8211;
        }
        set
        {
            bool __marshalledValue_8213;
            __marshalledValue_8213 = value;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "loop", __marshalledValue_8213);
        }
    }

    public double LoopStart
    {
        get
        {
            double __res_8214;
            double __res_8215 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "loopStart");
            __res_8214 = __res_8215;
            return __res_8214;
        }
        set
        {
            double __marshalledValue_8216;
            __marshalledValue_8216 = value;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "loopStart", __marshalledValue_8216);
        }
    }

    public double LoopEnd
    {
        get
        {
            double __res_8217;
            double __res_8218 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "loopEnd");
            __res_8217 = __res_8218;
            return __res_8217;
        }
        set
        {
            double __marshalledValue_8219;
            __marshalledValue_8219 = value;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "loopEnd", __marshalledValue_8219);
        }
    }
}

#nullable disable