// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class AudioEncoder(global::System.Runtime.InteropServices.JavaScript.JSObject obj): EventTarget(obj)
{
    public new global::Iskra.StdWeb.CodecState State
    {
        get
        {
            global::Iskra.StdWeb.CodecState __res_2607;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2608 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "state");
            throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = CodecState } not supported.");
            return __res_2607;
        }
    }

    public new uint EncodeQueueSize
    {
        get
        {
            uint __res_2609;
            double __res_2610 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "encodeQueueSize");
            __res_2609 = Convert.ToUInt32(__res_2610);
            return __res_2609;
        }
    }

    public new global::Iskra.StdWeb.EventHandlerNonNull? Ondequeue
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_2611;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_2612 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "ondequeue");
            if (__res_2612 is null)
            {
                __res_2611 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_2613 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_2612;
                throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } not supported.");
            }
            return __res_2611;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_2614;
            if (value is null)
            {
                __marshalledValue_2614 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_2615 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                throw new Exception("Marshaller ToJS from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } not supported.");
            }
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "ondequeue", __marshalledValue_2614);
        }
    }
}

#nullable disable