// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class AuthenticatorAssertionResponse(JSObject obj): AuthenticatorResponse(obj)
{
    public Iskra.JSCore.ArrayBuffer AuthenticatorData
    {
        get
        {
            Iskra.JSCore.ArrayBuffer __res_2841;
            JSObject __res_2842 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "authenticatorData");
            throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = ArrayBuffer } not supported.");
            return __res_2841;
        }
    }

    public Iskra.JSCore.ArrayBuffer Signature
    {
        get
        {
            Iskra.JSCore.ArrayBuffer __res_2843;
            JSObject __res_2844 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "signature");
            throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = ArrayBuffer } not supported.");
            return __res_2843;
        }
    }

    public Iskra.JSCore.ArrayBuffer? UserHandle
    {
        get
        {
            Iskra.JSCore.ArrayBuffer? __res_2845;
            JSObject? __res_2846 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "userHandle");
            if (__res_2846 is null)
            {
                __res_2845 = null;
            }
            else
            {
                JSObject __notNullable_2847 = (JSObject)__res_2846;
                throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = ArrayBuffer } not supported.");
            }
            return __res_2845;
        }
    }
}

#nullable disable