// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class ClipboardEvent(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.StdWeb.Event(obj)
{
    public static global::Iskra.StdWeb.ClipboardEvent New(string type)
    {
        int ___argsArrayLength_0 = 1;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_3 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        string ___marshalledValue_1;
        ___marshalledValue_1 = type;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(__argsArray_3.JSObject, 0, ___marshalledValue_1);

        global::System.Runtime.InteropServices.JavaScript.JSObject __res_5 = global::Iskra.JSCore.Extensions.JSConstructorExtensions.ConstructObjectNonEmpty(global::System.Runtime.InteropServices.JavaScript.JSHost.GlobalThis, "ClipboardEvent", __argsArray_3.JSObject);
        return new global::Iskra.StdWeb.ClipboardEvent(__res_5);
    }

    public static global::Iskra.StdWeb.ClipboardEvent New(string type, global::Iskra.StdWeb.ClipboardEventInit eventInitDict)
    {
        int ___argsArrayLength_0 = 2;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_0 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        string ___marshalledValue_1;
        ___marshalledValue_1 = type;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(__argsArray_0.JSObject, 0, ___marshalledValue_1);

        // Argument 2
        global::System.Runtime.InteropServices.JavaScript.JSObject ___marshalledValue_2;
        ___marshalledValue_2 = eventInitDict.JSObject;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(__argsArray_0.JSObject, 1, ___marshalledValue_2);

        global::System.Runtime.InteropServices.JavaScript.JSObject __res_2 = global::Iskra.JSCore.Extensions.JSConstructorExtensions.ConstructObjectNonEmpty(global::System.Runtime.InteropServices.JavaScript.JSHost.GlobalThis, "ClipboardEvent", __argsArray_0.JSObject);
        return new global::Iskra.StdWeb.ClipboardEvent(__res_2);
    }

    public global::Iskra.StdWeb.DataTransfer? ClipboardData
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.DataTransfer?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "clipboardData");
    }
}

#nullable disable