// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class CompositionEvent(global::System.Runtime.InteropServices.JavaScript.JSObject obj): UIEvent(obj)
{
    public string Data
    {
        get
        {
            string __res_8056;
            string __res_8057 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "data");
            __res_8056 = __res_8057;
            return __res_8056;
        }
    }
}

#nullable disable