// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public delegate string? CreateScriptURLCallbackManaged(string input, params global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>?[] arguments);

public partial class CreateScriptURLCallback(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public static implicit operator CreateScriptURLCallback(CreateScriptURLCallbackManaged input)
    {
        Action<global::System.Runtime.InteropServices.JavaScript.JSObject, global::System.Runtime.InteropServices.JavaScript.JSObject> callback = (__args_105, __res_115) =>
        {
            using (__args_105)
            using (__res_115)
            {
                // Argument 1
                string __arg_107;
                string __res_108 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(__args_105, 0);
                __arg_107 = __res_108;

                // Argument 2
                int __length_106 = global::System.Convert.ToInt32(global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(__args_105, "length"));
                int __paramsLength_110 = __length_106 - 1;
                global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>?[] __arg_109 = new global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>?[__paramsLength_110];
                for (int __i_111 = 0; __i_111 < __paramsLength_110; __i_111++)
                {
                    global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>? __paramsItem_112;

                    global::System.Runtime.InteropServices.JavaScript.JSObject? __propObject_113;
                    __propObject_113 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsUnionV2AsNullable(__args_105, 1 + __i_111);
                    if (__propObject_113 is null)
                    {
                        __paramsItem_112 = null;
                    }
                    else
                    {
                        __paramsItem_112 = new global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>(__propObject_113);
                    }

                    __arg_109[__i_111] = __paramsItem_112;
                }

                string? __managedRes_116 = input(__arg_107, __arg_109);

                string? __marshalledValue_117;
                if (__managedRes_116 is null)
                {
                    __marshalledValue_117 = null;
                }
                else
                {
                    string __notNullable_118 = (string)__managedRes_116;
                    __marshalledValue_117 = __notNullable_118;
                }
                global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2AsNullable(__res_115, "value", __marshalledValue_117);
            }
        };

        global::System.Runtime.InteropServices.JavaScript.JSObject __funcObj_114 = global::Iskra.JSCore.Extensions.JSFunctionExtensions.WrapAsNonVoidFunction(callback);
        global::Iskra.JSCore.Extensions.JSFunctionExtensions.StoreManagedFunctionToProperty(__funcObj_114, input); 

        return new global::Iskra.StdWeb.CreateScriptURLCallback(__funcObj_114);
    }

    public bool TryGetManaged([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] out global::Iskra.StdWeb.CreateScriptURLCallbackManaged? managed, bool allowConversion = false)
    {
        managed = global::Iskra.JSCore.Extensions.JSFunctionExtensions.GetManagedFunctionFromProperty(JSObject) as global::Iskra.StdWeb.CreateScriptURLCallbackManaged;
        if (managed is not null)
        {
            return true;
        }

        if (!allowConversion)
        {
            return false;
        }

        managed = (input, arguments) =>
        {
            int __argsArrayLength_122 = arguments.Length + 1;

            using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_119 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(__argsArrayLength_122);

            // Argument 1
            string __marshalledValue_123;
            __marshalledValue_123 = input;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(__argsArray_119.JSObject, 0, __marshalledValue_123);

            // Argument 2
            for (int __i_124 = 0; __i_124 < arguments.Length; __i_124++)
            {
            global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>? __elem_125 = arguments[__i_124];
                global::System.Runtime.InteropServices.JavaScript.JSObject? __propObject_126;
                if (__elem_125 is null)
                {
                    __propObject_126 = null;
                }
                else
                {
                    __propObject_126 = __elem_125.JSObject;
                }

                global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsUnionAsNullable(__argsArray_119.JSObject, 1 + __i_124, __propObject_126);
            }

            using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_120 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

            global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallNonEmptyNonVoidFunction(JSObject, null, __argsArray_119.JSObject, __resOwner_120.JSObject);

            // Return Value
            string? __res_121;
            string? __res_127 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2AsNullable(__resOwner_120.JSObject, "value");
            if (__res_127 is null)
            {
                __res_121 = null;
            }
            else
            {
                string __notNullable_128 = (string)__res_127;
                __res_121 = __notNullable_128;
            }
            return __res_121;
        };
        return true;
    }
}

#nullable disable