// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class CSSFontPaletteValuesRule(JSObject obj): CSSRule(obj)
{

}

#nullable disable