// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class CSSFontPaletteValuesRule(JSObject obj): CSSRule(obj)
{
    public object Name
    {
        get
        {
            throw new Exception();
        }
    }

    public object FontFamily
    {
        get
        {
            throw new Exception();
        }
    }

    public object BasePalette
    {
        get
        {
            throw new Exception();
        }
    }

    public object OverrideColors
    {
        get
        {
            throw new Exception();
        }
    }
}

#nullable disable