// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class CSSNamespaceRule(JSObject obj): CSSRule(obj)
{
    public object NamespaceURI
    {
        get
        {
            throw new Exception();
        }
    }

    public object Prefix
    {
        get
        {
            throw new Exception();
        }
    }
}

#nullable disable