// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class CSSParserDeclaration(JSObject obj): CSSParserRule(obj)
{
    public string Name
    {
        get
        {
            string __res_2957;
            throw new Exception();
            return __res_2957;
        }
    }

    public object Body
    {
        get
        {
            object __res_2958;
            throw new Exception();
            return __res_2958;
        }
    }
}

#nullable disable