// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class CSSRule(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public const ushort KEYFRAMES_RULE = 7;

    public const ushort KEYFRAME_RULE = 8;

    public const ushort SUPPORTS_RULE = 12;

    public string CssText
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<string, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "cssText");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<string, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "cssText", value);
    }

    public global::Iskra.StdWeb.CSSRule? ParentRule
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.CSSRule?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "parentRule");
    }

    public global::Iskra.StdWeb.CSSStyleSheet? ParentStyleSheet
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.CSSStyleSheet?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "parentStyleSheet");
    }

    public ushort Type
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<ushort, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "type");
    }

    public const ushort STYLE_RULE = 1;

    public const ushort CHARSET_RULE = 2;

    public const ushort IMPORT_RULE = 3;

    public const ushort MEDIA_RULE = 4;

    public const ushort FONT_FACE_RULE = 5;

    public const ushort PAGE_RULE = 6;

    public const ushort MARGIN_RULE = 9;

    public const ushort NAMESPACE_RULE = 10;

    public const ushort COUNTER_STYLE_RULE = 11;

    public const ushort FONT_FEATURE_VALUES_RULE = 14;
}

#nullable disable