// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class CustomEvent(global::System.Runtime.InteropServices.JavaScript.JSObject obj): Event(obj)
{
    public global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>? Detail
    {
        get
        {
            global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>? __res_4989;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __propObject_4990;
            __propObject_4990 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsUnionV2AsNullable(JSObject, "detail");
            if (__propObject_4990 is null)
            {
                __res_4989 = null;
            }
            else
            {
                __res_4989 = new global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>(__propObject_4990);
            }
            return __res_4989;
        }
    }
}

#nullable disable