// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class DeviceMotionEventAcceleration(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public double? X
    {
        get
        {
            double? __res_2893;
            double? __res_2894 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2AsNullable(JSObject, "x");
            if (__res_2894 is null)
            {
                __res_2893 = null;
            }
            else
            {
                double __notNullable_2895 = (double)__res_2894;
                __res_2893 = __notNullable_2895;
            }
            return __res_2893;
        }
    }

    public double? Y
    {
        get
        {
            double? __res_2896;
            double? __res_2897 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2AsNullable(JSObject, "y");
            if (__res_2897 is null)
            {
                __res_2896 = null;
            }
            else
            {
                double __notNullable_2898 = (double)__res_2897;
                __res_2896 = __notNullable_2898;
            }
            return __res_2896;
        }
    }

    public double? Z
    {
        get
        {
            double? __res_2899;
            double? __res_2900 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2AsNullable(JSObject, "z");
            if (__res_2900 is null)
            {
                __res_2899 = null;
            }
            else
            {
                double __notNullable_2901 = (double)__res_2900;
                __res_2899 = __notNullable_2901;
            }
            return __res_2899;
        }
    }
}

#nullable disable