// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class DOMQuad(JSObject obj): JSObjectProxy(obj)
{
    public object P1
    {
        get
        {
            throw new Exception();
        }
    }

    public object P2
    {
        get
        {
            throw new Exception();
        }
    }

    public object P3
    {
        get
        {
            throw new Exception();
        }
    }

    public object P4
    {
        get
        {
            throw new Exception();
        }
    }
}

#nullable disable