// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class DOMRectReadOnly(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public double X
    {
        get
        {
            double __res_6158;
            double __res_6159 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "x");
            __res_6158 = __res_6159;
            return __res_6158;
        }
    }

    public double Y
    {
        get
        {
            double __res_6160;
            double __res_6161 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "y");
            __res_6160 = __res_6161;
            return __res_6160;
        }
    }

    public double Width
    {
        get
        {
            double __res_6162;
            double __res_6163 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "width");
            __res_6162 = __res_6163;
            return __res_6162;
        }
    }

    public double Height
    {
        get
        {
            double __res_6164;
            double __res_6165 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "height");
            __res_6164 = __res_6165;
            return __res_6164;
        }
    }

    public double Top
    {
        get
        {
            double __res_6166;
            double __res_6167 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "top");
            __res_6166 = __res_6167;
            return __res_6166;
        }
    }

    public double Right
    {
        get
        {
            double __res_6168;
            double __res_6169 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "right");
            __res_6168 = __res_6169;
            return __res_6168;
        }
    }

    public double Bottom
    {
        get
        {
            double __res_6170;
            double __res_6171 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "bottom");
            __res_6170 = __res_6171;
            return __res_6170;
        }
    }

    public double Left
    {
        get
        {
            double __res_6172;
            double __res_6173 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "left");
            __res_6172 = __res_6173;
            return __res_6172;
        }
    }
}

#nullable disable