// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class Event(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public string Type
    {
        get
        {
            string __res_4958;
            string __res_4959 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "type");
            __res_4958 = __res_4959;
            return __res_4958;
        }
    }

    public global::Iskra.StdWeb.EventTarget? Target
    {
        get
        {
            global::Iskra.StdWeb.EventTarget? __res_4960;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_4961 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "target");
            if (__res_4961 is null)
            {
                __res_4960 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_4962 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_4961;
                __res_4960 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.EventTarget>(__notNullable_4962);
            }
            return __res_4960;
        }
    }

    public global::Iskra.StdWeb.EventTarget? SrcElement
    {
        get
        {
            global::Iskra.StdWeb.EventTarget? __res_4963;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_4964 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "srcElement");
            if (__res_4964 is null)
            {
                __res_4963 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_4965 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_4964;
                __res_4963 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.EventTarget>(__notNullable_4965);
            }
            return __res_4963;
        }
    }

    public global::Iskra.StdWeb.EventTarget? CurrentTarget
    {
        get
        {
            global::Iskra.StdWeb.EventTarget? __res_4966;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_4967 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "currentTarget");
            if (__res_4967 is null)
            {
                __res_4966 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_4968 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_4967;
                __res_4966 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.EventTarget>(__notNullable_4968);
            }
            return __res_4966;
        }
    }

    public ushort EventPhase
    {
        get
        {
            ushort __res_4969;
            double __res_4970 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "eventPhase");
            __res_4969 = Convert.ToUInt16(__res_4970);
            return __res_4969;
        }
    }

    public bool CancelBubble
    {
        get
        {
            bool __res_4971;
            bool __res_4972 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "cancelBubble");
            __res_4971 = __res_4972;
            return __res_4971;
        }
        set
        {
            bool __marshalledValue_4973;
            __marshalledValue_4973 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "cancelBubble", __marshalledValue_4973);
        }
    }

    public bool Bubbles
    {
        get
        {
            bool __res_4974;
            bool __res_4975 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "bubbles");
            __res_4974 = __res_4975;
            return __res_4974;
        }
    }

    public bool Cancelable
    {
        get
        {
            bool __res_4976;
            bool __res_4977 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "cancelable");
            __res_4976 = __res_4977;
            return __res_4976;
        }
    }

    public bool ReturnValue
    {
        get
        {
            bool __res_4978;
            bool __res_4979 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "returnValue");
            __res_4978 = __res_4979;
            return __res_4978;
        }
        set
        {
            bool __marshalledValue_4980;
            __marshalledValue_4980 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "returnValue", __marshalledValue_4980);
        }
    }

    public bool DefaultPrevented
    {
        get
        {
            bool __res_4981;
            bool __res_4982 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "defaultPrevented");
            __res_4981 = __res_4982;
            return __res_4981;
        }
    }

    public bool Composed
    {
        get
        {
            bool __res_4983;
            bool __res_4984 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "composed");
            __res_4983 = __res_4984;
            return __res_4983;
        }
    }

    public bool IsTrusted
    {
        get
        {
            bool __res_4985;
            bool __res_4986 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "isTrusted");
            __res_4985 = __res_4986;
            return __res_4985;
        }
    }

    public double TimeStamp
    {
        get
        {
            double __res_4987;
            double __res_4988 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "timeStamp");
            __res_4987 = __res_4988;
            return __res_4987;
        }
    }
}

#nullable disable