// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class Exception(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public string? Stack
    {
        get
        {
            string? __res_7974;
            string? __res_7975 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2AsNullable(JSObject, "stack");
            if (__res_7975 is null)
            {
                __res_7974 = null;
            }
            else
            {
                string __notNullable_7976 = (string)__res_7975;
                __res_7974 = __notNullable_7976;
            }
            return __res_7974;
        }
    }
}

#nullable disable