// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class FileSystemHandle(JSObject obj): JSObjectProxy(obj)
{
    public Iskra.StdWeb.FileSystemHandleKind Kind
    {
        get
        {
            Iskra.StdWeb.FileSystemHandleKind __res_1616;
            throw new Exception();
            return __res_1616;
        }
    }

    public string Name
    {
        get
        {
            string __res_1617;
            throw new Exception();
            return __res_1617;
        }
    }
}

#nullable disable