// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class File(JSObject obj): Blob(obj)
{
    public string Name
    {
        get
        {
            string __res_7970;
            string __res_7971 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "name");
            __res_7970 = __res_7971;
            return __res_7970;
        }
    }

    public long LastModified
    {
        get
        {
            long __res_7972;
            double __res_7973 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "lastModified");
            __res_7972 = Convert.ToInt64(__res_7973);
            return __res_7972;
        }
    }
}

#nullable disable