// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class FontFaceSetLoadEvent(JSObject obj): Event(obj)
{
    public global::Iskra.JSCore.Generics.FrozenArray<Iskra.StdWeb.FontFace, global::Iskra.StdWeb.GenericMarshaller.Value_16> Fontfaces
    {
        get
        {
            global::Iskra.JSCore.Generics.FrozenArray<Iskra.StdWeb.FontFace, global::Iskra.StdWeb.GenericMarshaller.Value_16> __res_2133;
            JSObject __propObject_2134;
            __propObject_2134 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "fontfaces");
            __res_2133 = new global::Iskra.JSCore.Generics.FrozenArray<Iskra.StdWeb.FontFace, global::Iskra.StdWeb.GenericMarshaller.Value_16>(__propObject_2134);
            return __res_2133;
        }
    }
}

#nullable disable