// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public delegate global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>? FunctionManaged(params global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>?[] arguments);

public partial class Function(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public static implicit operator Function(FunctionManaged input)
    {
        Action<global::System.Runtime.InteropServices.JavaScript.JSObject, global::System.Runtime.InteropServices.JavaScript.JSObject> callback = (__args_6375, __res_6383) =>
        {
            using (__args_6375)
            using (__res_6383)
            {
                // Argument 1
                int __length_6376 = global::System.Convert.ToInt32(global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(__args_6375, "length"));
                int __paramsLength_6378 = __length_6376 - 0;
                global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>?[] __arg_6377 = new global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>?[__paramsLength_6378];
                for (int __i_6379 = 0; __i_6379 < __paramsLength_6378; __i_6379++)
                {
                    global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>? __paramsItem_6380;

                    global::System.Runtime.InteropServices.JavaScript.JSObject? __propObject_6381;
                    __propObject_6381 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsUnionV2AsNullable(__args_6375, 0 + __i_6379);
                    if (__propObject_6381 is null)
                    {
                        __paramsItem_6380 = null;
                    }
                    else
                    {
                        __paramsItem_6380 = new global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>(__propObject_6381);
                    }

                    __arg_6377[__i_6379] = __paramsItem_6380;
                }

                global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>? __managedRes_6384 = input(__arg_6377);

                global::System.Runtime.InteropServices.JavaScript.JSObject? __propObject_6385;
                if (__managedRes_6384 is null)
                {
                    __propObject_6385 = null;
                }
                else
                {
                    __propObject_6385 = __managedRes_6384.JSObject;
                }

                global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsUnionAsNullable(__res_6383, "value", __propObject_6385);
            }
        };

        global::System.Runtime.InteropServices.JavaScript.JSObject __funcObj_6382 = global::Iskra.JSCore.Extensions.JSFunctionExtensions.WrapAsNonVoidFunction(callback);
        global::Iskra.JSCore.Extensions.JSFunctionExtensions.StoreManagedFunctionToProperty(__funcObj_6382, input); 

        return new global::Iskra.StdWeb.Function(__funcObj_6382);
    }

    public bool TryGetManaged([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] out global::Iskra.StdWeb.FunctionManaged? managed, bool allowConversion = false)
    {
        managed = global::Iskra.JSCore.Extensions.JSFunctionExtensions.GetManagedFunctionFromProperty(JSObject) as global::Iskra.StdWeb.FunctionManaged;
        if (managed is not null)
        {
            return true;
        }

        if (!allowConversion)
        {
            return false;
        }

        managed = (arguments) =>
        {
            int __argsArrayLength_6389 = arguments.Length + 0;

            using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_6386 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(__argsArrayLength_6389);

            // Argument 1
            for (int __i_6390 = 0; __i_6390 < arguments.Length; __i_6390++)
            {
            global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>? __elem_6391 = arguments[__i_6390];
                global::System.Runtime.InteropServices.JavaScript.JSObject? __propObject_6392;
                if (__elem_6391 is null)
                {
                    __propObject_6392 = null;
                }
                else
                {
                    __propObject_6392 = __elem_6391.JSObject;
                }

                global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsUnionAsNullable(__argsArray_6386.JSObject, 0 + __i_6390, __propObject_6392);
            }

            using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_6387 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

            global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallNonEmptyNonVoidFunction(JSObject, null, __argsArray_6386.JSObject, __resOwner_6387.JSObject);

            // Return Value
            global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>? __res_6388;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __propObject_6393;
            __propObject_6393 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsUnionV2AsNullable(__resOwner_6387.JSObject, "value");
            if (__propObject_6393 is null)
            {
                __res_6388 = null;
            }
            else
            {
                __res_6388 = new global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>(__propObject_6393);
            }
            return __res_6388;
        };
        return true;
    }
}

#nullable disable