// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class HashChangeEvent(global::System.Runtime.InteropServices.JavaScript.JSObject obj): Event(obj)
{
    public string OldURL
    {
        get
        {
            string __res_11718;
            string __res_11719 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "oldURL");
            __res_11718 = __res_11719;
            return __res_11718;
        }
    }

    public string NewURL
    {
        get
        {
            string __res_11720;
            string __res_11721 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "newURL");
            __res_11720 = __res_11721;
            return __res_11720;
        }
    }
}

#nullable disable