// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class HID(JSObject obj): EventTarget(obj)
{
    public EventHandler Onconnect
    {
        get
        {
            throw new Exception();
        }
        set
        {
            throw new Exception();
        }
    }

    public EventHandler Ondisconnect
    {
        get
        {
            throw new Exception();
        }
        set
        {
            throw new Exception();
        }
    }
}

#nullable disable