// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class HTMLVideoElement(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public global::Iskra.StdWeb.EventHandlerNonNull? Onenterpictureinpicture
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_10023;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_10024 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onenterpictureinpicture");
            if (__res_10024 is null)
            {
                __res_10023 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_10025 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_10024;
                __res_10023 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_10025);
            }
            return __res_10023;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_10026;
            if (value is null)
            {
                __marshalledValue_10026 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_10027 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_10026 = __notNullable_10027.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onenterpictureinpicture", __marshalledValue_10026);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onleavepictureinpicture
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_10028;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_10029 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onleavepictureinpicture");
            if (__res_10029 is null)
            {
                __res_10028 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_10030 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_10029;
                __res_10028 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_10030);
            }
            return __res_10028;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_10031;
            if (value is null)
            {
                __marshalledValue_10031 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_10032 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_10031 = __notNullable_10032.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onleavepictureinpicture", __marshalledValue_10031);
        }
    }

    public bool DisablePictureInPicture
    {
        get
        {
            bool __res_10033;
            bool __res_10034 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "disablePictureInPicture");
            __res_10033 = __res_10034;
            return __res_10033;
        }
        set
        {
            bool __marshalledValue_10035;
            __marshalledValue_10035 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "disablePictureInPicture", __marshalledValue_10035);
        }
    }

    public uint Width
    {
        get
        {
            uint __res_10036;
            double __res_10037 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "width");
            __res_10036 = Convert.ToUInt32(__res_10037);
            return __res_10036;
        }
        set
        {
            double __marshalledValue_10038;
            __marshalledValue_10038 = Convert.ToDouble(value);
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "width", __marshalledValue_10038);
        }
    }

    public uint Height
    {
        get
        {
            uint __res_10039;
            double __res_10040 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "height");
            __res_10039 = Convert.ToUInt32(__res_10040);
            return __res_10039;
        }
        set
        {
            double __marshalledValue_10041;
            __marshalledValue_10041 = Convert.ToDouble(value);
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "height", __marshalledValue_10041);
        }
    }

    public uint VideoWidth
    {
        get
        {
            uint __res_10042;
            double __res_10043 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "videoWidth");
            __res_10042 = Convert.ToUInt32(__res_10043);
            return __res_10042;
        }
    }

    public uint VideoHeight
    {
        get
        {
            uint __res_10044;
            double __res_10045 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "videoHeight");
            __res_10044 = Convert.ToUInt32(__res_10045);
            return __res_10044;
        }
    }

    public string Poster
    {
        get
        {
            string __res_10046;
            string __res_10047 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "poster");
            __res_10046 = __res_10047;
            return __res_10046;
        }
        set
        {
            string __marshalledValue_10048;
            __marshalledValue_10048 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "poster", __marshalledValue_10048);
        }
    }

    public bool PlaysInline
    {
        get
        {
            bool __res_10049;
            bool __res_10050 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "playsInline");
            __res_10049 = __res_10050;
            return __res_10049;
        }
        set
        {
            bool __marshalledValue_10051;
            __marshalledValue_10051 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "playsInline", __marshalledValue_10051);
        }
    }
}

#nullable disable