// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class HTMLMeterElement(global::System.Runtime.InteropServices.JavaScript.JSObject obj): HTMLElement(obj)
{
    public double Value
    {
        get
        {
            double __res_10094;
            double __res_10095 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "value");
            __res_10094 = __res_10095;
            return __res_10094;
        }
        set
        {
            double __marshalledValue_10096;
            __marshalledValue_10096 = value;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "value", __marshalledValue_10096);
        }
    }

    public double Min
    {
        get
        {
            double __res_10097;
            double __res_10098 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "min");
            __res_10097 = __res_10098;
            return __res_10097;
        }
        set
        {
            double __marshalledValue_10099;
            __marshalledValue_10099 = value;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "min", __marshalledValue_10099);
        }
    }

    public double Max
    {
        get
        {
            double __res_10100;
            double __res_10101 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "max");
            __res_10100 = __res_10101;
            return __res_10100;
        }
        set
        {
            double __marshalledValue_10102;
            __marshalledValue_10102 = value;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "max", __marshalledValue_10102);
        }
    }

    public double Low
    {
        get
        {
            double __res_10103;
            double __res_10104 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "low");
            __res_10103 = __res_10104;
            return __res_10103;
        }
        set
        {
            double __marshalledValue_10105;
            __marshalledValue_10105 = value;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "low", __marshalledValue_10105);
        }
    }

    public double High
    {
        get
        {
            double __res_10106;
            double __res_10107 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "high");
            __res_10106 = __res_10107;
            return __res_10106;
        }
        set
        {
            double __marshalledValue_10108;
            __marshalledValue_10108 = value;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "high", __marshalledValue_10108);
        }
    }

    public double Optimum
    {
        get
        {
            double __res_10109;
            double __res_10110 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "optimum");
            __res_10109 = __res_10110;
            return __res_10109;
        }
        set
        {
            double __marshalledValue_10111;
            __marshalledValue_10111 = value;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "optimum", __marshalledValue_10111);
        }
    }

    public global::Iskra.StdWeb.NodeList Labels
    {
        get
        {
            global::Iskra.StdWeb.NodeList __res_10112;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_10113 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "labels");
            __res_10112 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.NodeList>(__res_10113);
            return __res_10112;
        }
    }
}

#nullable disable