// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class HTMLCanvasElement(global::System.Runtime.InteropServices.JavaScript.JSObject obj): HTMLElement(obj)
{
    public uint Width
    {
        get
        {
            uint __res_6496;
            double __res_6497 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "width");
            __res_6496 = Convert.ToUInt32(__res_6497);
            return __res_6496;
        }
        set
        {
            double __marshalledValue_6498;
            __marshalledValue_6498 = Convert.ToDouble(value);
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "width", __marshalledValue_6498);
        }
    }

    public uint Height
    {
        get
        {
            uint __res_6499;
            double __res_6500 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "height");
            __res_6499 = Convert.ToUInt32(__res_6500);
            return __res_6499;
        }
        set
        {
            double __marshalledValue_6501;
            __marshalledValue_6501 = Convert.ToDouble(value);
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "height", __marshalledValue_6501);
        }
    }
}

#nullable disable