// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class HTMLTemplateElement(global::System.Runtime.InteropServices.JavaScript.JSObject obj): HTMLElement(obj)
{
    public global::Iskra.StdWeb.DocumentFragment Content
    {
        get
        {
            global::Iskra.StdWeb.DocumentFragment __res_10669;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_10670 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "content");
            __res_10669 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.DocumentFragment>(__res_10670);
            return __res_10669;
        }
    }

    public string ShadowRootMode
    {
        get
        {
            string __res_10671;
            string __res_10672 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "shadowRootMode");
            __res_10671 = __res_10672;
            return __res_10671;
        }
        set
        {
            string __marshalledValue_10673;
            __marshalledValue_10673 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "shadowRootMode", __marshalledValue_10673);
        }
    }

    public bool ShadowRootDelegatesFocus
    {
        get
        {
            bool __res_10674;
            bool __res_10675 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "shadowRootDelegatesFocus");
            __res_10674 = __res_10675;
            return __res_10674;
        }
        set
        {
            bool __marshalledValue_10676;
            __marshalledValue_10676 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "shadowRootDelegatesFocus", __marshalledValue_10676);
        }
    }

    public bool ShadowRootClonable
    {
        get
        {
            bool __res_10677;
            bool __res_10678 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "shadowRootClonable");
            __res_10677 = __res_10678;
            return __res_10677;
        }
        set
        {
            bool __marshalledValue_10679;
            __marshalledValue_10679 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "shadowRootClonable", __marshalledValue_10679);
        }
    }

    public bool ShadowRootSerializable
    {
        get
        {
            bool __res_10680;
            bool __res_10681 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "shadowRootSerializable");
            __res_10680 = __res_10681;
            return __res_10680;
        }
        set
        {
            bool __marshalledValue_10682;
            __marshalledValue_10682 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "shadowRootSerializable", __marshalledValue_10682);
        }
    }

    public string ShadowRootCustomElementRegistry
    {
        get
        {
            string __res_10683;
            string __res_10684 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "shadowRootCustomElementRegistry");
            __res_10683 = __res_10684;
            return __res_10683;
        }
        set
        {
            string __marshalledValue_10685;
            __marshalledValue_10685 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "shadowRootCustomElementRegistry", __marshalledValue_10685);
        }
    }
}

#nullable disable