// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class HTMLDirectoryElement(JSObject obj): HTMLElement(obj)
{
    public bool Compact
    {
        get
        {
            bool __res_2769;
            __res_2769 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "compact");
            return __res_2769;
        }
        set
        {
            throw new Exception();
        }
    }
}

#nullable disable