// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class HTMLObjectElement(JSObject obj): HTMLElement(obj)
{
    public string Data
    {
        get
        {
            throw new Exception();
        }
        set
        {
            throw new Exception();
        }
    }

    public string Type
    {
        get
        {
            throw new Exception();
        }
        set
        {
            throw new Exception();
        }
    }

    public string Name
    {
        get
        {
            throw new Exception();
        }
        set
        {
            throw new Exception();
        }
    }

    public HTMLFormElement? Form
    {
        get
        {
            throw new Exception();
        }
    }

    public string Width
    {
        get
        {
            throw new Exception();
        }
        set
        {
            throw new Exception();
        }
    }

    public string Height
    {
        get
        {
            throw new Exception();
        }
        set
        {
            throw new Exception();
        }
    }

    public Document? ContentDocument
    {
        get
        {
            throw new Exception();
        }
    }

    public Window? ContentWindow
    {
        get
        {
            throw new Exception();
        }
    }

    public bool WillValidate
    {
        get
        {
            throw new Exception();
        }
    }

    public ValidityState Validity
    {
        get
        {
            throw new Exception();
        }
    }

    public string ValidationMessage
    {
        get
        {
            throw new Exception();
        }
    }
}

#nullable disable