// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class HTMLOListElement(JSObject obj): HTMLElement(obj)
{
    public bool Reversed
    {
        get
        {
            bool __res_5375;
            bool __res_5376 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "reversed");
            __res_5375 = __res_5376;
            return __res_5375;
        }
        set
        {
            bool __marshalledValue_5377;
            __marshalledValue_5377 = value;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "reversed", __marshalledValue_5377);
        }
    }

    public int Start
    {
        get
        {
            int __res_5378;
            double __res_5379 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "start");
            __res_5378 = Convert.ToInt32(__res_5379);
            return __res_5378;
        }
        set
        {
            double __marshalledValue_5380;
            __marshalledValue_5380 = Convert.ToDouble(value);
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "start", __marshalledValue_5380);
        }
    }

    public string Type
    {
        get
        {
            string __res_5381;
            string __res_5382 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "type");
            __res_5381 = __res_5382;
            return __res_5381;
        }
        set
        {
            string __marshalledValue_5383;
            __marshalledValue_5383 = value;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "type", __marshalledValue_5383);
        }
    }
}

#nullable disable