// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class IDBIndex(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public string Name
    {
        get
        {
            string __res_14077;
            string __res_14078 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "name");
            __res_14077 = __res_14078;
            return __res_14077;
        }
        set
        {
            string __marshalledValue_14079;
            __marshalledValue_14079 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "name", __marshalledValue_14079);
        }
    }

    public global::Iskra.StdWeb.IDBObjectStore ObjectStore
    {
        get
        {
            global::Iskra.StdWeb.IDBObjectStore __res_14080;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_14081 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "objectStore");
            __res_14080 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.IDBObjectStore>(__res_14081);
            return __res_14080;
        }
    }

    public global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>? KeyPath
    {
        get
        {
            global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>? __res_14082;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __propObject_14083;
            __propObject_14083 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsUnionV2AsNullable(JSObject, "keyPath");
            if (__propObject_14083 is null)
            {
                __res_14082 = null;
            }
            else
            {
                __res_14082 = new global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>(__propObject_14083);
            }
            return __res_14082;
        }
    }

    public bool MultiEntry
    {
        get
        {
            bool __res_14084;
            bool __res_14085 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "multiEntry");
            __res_14084 = __res_14085;
            return __res_14084;
        }
    }

    public bool Unique
    {
        get
        {
            bool __res_14086;
            bool __res_14087 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "unique");
            __res_14086 = __res_14087;
            return __res_14086;
        }
    }
}

#nullable disable