// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class IDBObjectStore(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public string Name
    {
        get
        {
            string __res_7809;
            string __res_7810 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "name");
            __res_7809 = __res_7810;
            return __res_7809;
        }
        set
        {
            string __marshalledValue_7811;
            __marshalledValue_7811 = value;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "name", __marshalledValue_7811);
        }
    }

    public object? KeyPath
    {
        get
        {
            object? __res_7812;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_7813 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "keyPath");
            throw new global::System.Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = any } not supported.");
            return __res_7812;
        }
    }

    public global::Iskra.StdWeb.DOMStringList IndexNames
    {
        get
        {
            global::Iskra.StdWeb.DOMStringList __res_7814;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_7815 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "indexNames");
            __res_7814 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.DOMStringList>(__res_7815);
            return __res_7814;
        }
    }

    public global::Iskra.StdWeb.IDBTransaction Transaction
    {
        get
        {
            global::Iskra.StdWeb.IDBTransaction __res_7816;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_7817 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "transaction");
            __res_7816 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.IDBTransaction>(__res_7817);
            return __res_7816;
        }
    }

    public bool AutoIncrement
    {
        get
        {
            bool __res_7818;
            bool __res_7819 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "autoIncrement");
            __res_7818 = __res_7819;
            return __res_7818;
        }
    }
}

#nullable disable