// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class IDBTransaction(global::System.Runtime.InteropServices.JavaScript.JSObject obj): EventTarget(obj)
{
    public global::Iskra.StdWeb.DOMStringList ObjectStoreNames
    {
        get
        {
            global::Iskra.StdWeb.DOMStringList __res_13514;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_13515 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "objectStoreNames");
            __res_13514 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.DOMStringList>(__res_13515);
            return __res_13514;
        }
    }

    public global::Iskra.StdWeb.IDBTransactionMode Mode
    {
        get
        {
            global::Iskra.StdWeb.IDBTransactionMode __res_13516;
            string __res_13517 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "mode");
            __res_13516 = global::Iskra.StdWeb.IDBTransactionMode.Create(__res_13517);
            return __res_13516;
        }
    }

    public global::Iskra.StdWeb.IDBTransactionDurability Durability
    {
        get
        {
            global::Iskra.StdWeb.IDBTransactionDurability __res_13518;
            string __res_13519 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "durability");
            __res_13518 = global::Iskra.StdWeb.IDBTransactionDurability.Create(__res_13519);
            return __res_13518;
        }
    }

    public global::Iskra.StdWeb.IDBDatabase Db
    {
        get
        {
            global::Iskra.StdWeb.IDBDatabase __res_13520;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_13521 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "db");
            __res_13520 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.IDBDatabase>(__res_13521);
            return __res_13520;
        }
    }

    public global::Iskra.StdWeb.DOMException? Error
    {
        get
        {
            global::Iskra.StdWeb.DOMException? __res_13522;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_13523 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "error");
            if (__res_13523 is null)
            {
                __res_13522 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_13524 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_13523;
                __res_13522 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.DOMException>(__notNullable_13524);
            }
            return __res_13522;
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onabort
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_13525;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_13526 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onabort");
            if (__res_13526 is null)
            {
                __res_13525 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_13527 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_13526;
                __res_13525 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_13527);
            }
            return __res_13525;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_13528;
            if (value is null)
            {
                __marshalledValue_13528 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_13529 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_13528 = __notNullable_13529.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onabort", __marshalledValue_13528);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Oncomplete
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_13530;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_13531 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "oncomplete");
            if (__res_13531 is null)
            {
                __res_13530 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_13532 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_13531;
                __res_13530 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_13532);
            }
            return __res_13530;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_13533;
            if (value is null)
            {
                __marshalledValue_13533 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_13534 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_13533 = __notNullable_13534.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "oncomplete", __marshalledValue_13533);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onerror
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_13535;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_13536 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onerror");
            if (__res_13536 is null)
            {
                __res_13535 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_13537 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_13536;
                __res_13535 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_13537);
            }
            return __res_13535;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_13538;
            if (value is null)
            {
                __marshalledValue_13538 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_13539 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_13538 = __notNullable_13539.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onerror", __marshalledValue_13538);
        }
    }
}

#nullable disable