// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class IdentityCredentialError(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.StdWeb.DOMException(obj)
{
    public static global::Iskra.StdWeb.IdentityCredentialError New()
    {
        global::System.Runtime.InteropServices.JavaScript.JSObject __res_8 = global::Iskra.JSCore.Extensions.JSConstructorExtensions.ConstructObjectEmpty(global::System.Runtime.InteropServices.JavaScript.JSHost.GlobalThis, "IdentityCredentialError");
        return new global::Iskra.StdWeb.IdentityCredentialError(__res_8);
    }

    public static global::Iskra.StdWeb.IdentityCredentialError New(string message)
    {
        int ___argsArrayLength_0 = 1;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_3 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        string ___marshalledValue_1;
        ___marshalledValue_1 = message;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(__argsArray_3.JSObject, 0, ___marshalledValue_1);

        global::System.Runtime.InteropServices.JavaScript.JSObject __res_5 = global::Iskra.JSCore.Extensions.JSConstructorExtensions.ConstructObjectNonEmpty(global::System.Runtime.InteropServices.JavaScript.JSHost.GlobalThis, "IdentityCredentialError", __argsArray_3.JSObject);
        return new global::Iskra.StdWeb.IdentityCredentialError(__res_5);
    }

    public static global::Iskra.StdWeb.IdentityCredentialError New(string message, global::Iskra.StdWeb.IdentityCredentialErrorInit options)
    {
        int ___argsArrayLength_0 = 2;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_0 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        string ___marshalledValue_1;
        ___marshalledValue_1 = message;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(__argsArray_0.JSObject, 0, ___marshalledValue_1);

        // Argument 2
        global::System.Runtime.InteropServices.JavaScript.JSObject ___marshalledValue_2;
        ___marshalledValue_2 = options.JSObject;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(__argsArray_0.JSObject, 1, ___marshalledValue_2);

        global::System.Runtime.InteropServices.JavaScript.JSObject __res_2 = global::Iskra.JSCore.Extensions.JSConstructorExtensions.ConstructObjectNonEmpty(global::System.Runtime.InteropServices.JavaScript.JSHost.GlobalThis, "IdentityCredentialError", __argsArray_0.JSObject);
        return new global::Iskra.StdWeb.IdentityCredentialError(__res_2);
    }

    public string Error
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<string, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "error");
    }

    public string Url
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<string, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "url");
    }
}

#nullable disable