// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;

namespace Iskra.StdWeb;

#nullable enable

public delegate void IntersectionObserverCallback(object entries, Iskra.StdWeb.IntersectionObserver observer);

#nullable disable