// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class IntrinsicSizes(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public double MinContentSize
    {
        get
        {
            double __res_14193;
            double __res_14194 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "minContentSize");
            __res_14193 = __res_14194;
            return __res_14193;
        }
    }

    public double MaxContentSize
    {
        get
        {
            double __res_14195;
            double __res_14196 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "maxContentSize");
            __res_14195 = __res_14196;
            return __res_14195;
        }
    }
}

#nullable disable