// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class KeyFrameRequestEvent(global::System.Runtime.InteropServices.JavaScript.JSObject obj): Event(obj)
{
    public string? Rid
    {
        get
        {
            string? __res_2157;
            string? __res_2158 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2AsNullable(JSObject, "rid");
            if (__res_2158 is null)
            {
                __res_2157 = null;
            }
            else
            {
                string __notNullable_2159 = (string)__res_2158;
                __res_2157 = __notNullable_2159;
            }
            return __res_2157;
        }
    }
}

#nullable disable