// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class KeyFrameRequestEvent(global::System.Runtime.InteropServices.JavaScript.JSObject obj): Event(obj)
{
    public string? Rid
    {
        get
        {
            string? __res_2646;
            string? __res_2647 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2AsNullable(JSObject, "rid");
            if (__res_2647 is null)
            {
                __res_2646 = null;
            }
            else
            {
                string __notNullable_2648 = (string)__res_2647;
                __res_2646 = __notNullable_2648;
            }
            return __res_2646;
        }
    }
}

#nullable disable