// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class LayoutConstraints(JSObject obj): JSObjectProxy(obj)
{
    public double AvailableInlineSize
    {
        get
        {
            double __res_3071;
            throw new Exception();
            return __res_3071;
        }
    }

    public double AvailableBlockSize
    {
        get
        {
            double __res_3072;
            throw new Exception();
            return __res_3072;
        }
    }

    public double? FixedInlineSize
    {
        get
        {
            double? __res_3073;
            throw new Exception();
            return __res_3073;
        }
    }

    public double? FixedBlockSize
    {
        get
        {
            double? __res_3074;
            throw new Exception();
            return __res_3074;
        }
    }

    public double PercentageInlineSize
    {
        get
        {
            double __res_3075;
            throw new Exception();
            return __res_3075;
        }
    }

    public double PercentageBlockSize
    {
        get
        {
            double __res_3076;
            throw new Exception();
            return __res_3076;
        }
    }

    public double? BlockFragmentationOffset
    {
        get
        {
            double? __res_3077;
            throw new Exception();
            return __res_3077;
        }
    }

    public Iskra.StdWeb.BlockFragmentationType BlockFragmentationType
    {
        get
        {
            Iskra.StdWeb.BlockFragmentationType __res_3078;
            throw new Exception();
            return __res_3078;
        }
    }

    public object? Data
    {
        get
        {
            object? __res_3079;
            throw new Exception();
            return __res_3079;
        }
    }
}

#nullable disable