// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class MediaRecorder(JSObject obj): EventTarget(obj)
{
    public Iskra.StdWeb.MediaStream Stream
    {
        get
        {
            Iskra.StdWeb.MediaStream __res_3839;
            JSObject __res_3840 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "stream");
            throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = MediaStream } not supported.");
            return __res_3839;
        }
    }

    public string MimeType
    {
        get
        {
            string __res_3841;
            string __res_3842 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "mimeType");
            __res_3841 = __res_3842;
            return __res_3841;
        }
    }

    public Iskra.StdWeb.RecordingState State
    {
        get
        {
            Iskra.StdWeb.RecordingState __res_3843;
            JSObject __res_3844 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "state");
            throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = RecordingState } not supported.");
            return __res_3843;
        }
    }

    public Iskra.StdWeb.EventHandlerNonNull? Onstart
    {
        get
        {
            Iskra.StdWeb.EventHandlerNonNull? __res_3845;
            JSObject? __res_3846 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onstart");
            if (__res_3846 is null)
            {
                __res_3845 = null;
            }
            else
            {
                JSObject __notNullable_3847 = (JSObject)__res_3846;
                throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } not supported.");
            }
            return __res_3845;
        }
        set
        {
            JSObject? __marshalledValue_3848;
            if (value is null)
            {
                __marshalledValue_3848 = null;
            }
            else
            {
                Iskra.StdWeb.EventHandlerNonNull __notNullable_3849 = (Iskra.StdWeb.EventHandlerNonNull)value;
                throw new Exception("Marshaller ToJS from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } not supported.");
            }
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onstart", __marshalledValue_3848);
        }
    }

    public Iskra.StdWeb.EventHandlerNonNull? Onstop
    {
        get
        {
            Iskra.StdWeb.EventHandlerNonNull? __res_3850;
            JSObject? __res_3851 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onstop");
            if (__res_3851 is null)
            {
                __res_3850 = null;
            }
            else
            {
                JSObject __notNullable_3852 = (JSObject)__res_3851;
                throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } not supported.");
            }
            return __res_3850;
        }
        set
        {
            JSObject? __marshalledValue_3853;
            if (value is null)
            {
                __marshalledValue_3853 = null;
            }
            else
            {
                Iskra.StdWeb.EventHandlerNonNull __notNullable_3854 = (Iskra.StdWeb.EventHandlerNonNull)value;
                throw new Exception("Marshaller ToJS from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } not supported.");
            }
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onstop", __marshalledValue_3853);
        }
    }

    public Iskra.StdWeb.EventHandlerNonNull? Ondataavailable
    {
        get
        {
            Iskra.StdWeb.EventHandlerNonNull? __res_3855;
            JSObject? __res_3856 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "ondataavailable");
            if (__res_3856 is null)
            {
                __res_3855 = null;
            }
            else
            {
                JSObject __notNullable_3857 = (JSObject)__res_3856;
                throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } not supported.");
            }
            return __res_3855;
        }
        set
        {
            JSObject? __marshalledValue_3858;
            if (value is null)
            {
                __marshalledValue_3858 = null;
            }
            else
            {
                Iskra.StdWeb.EventHandlerNonNull __notNullable_3859 = (Iskra.StdWeb.EventHandlerNonNull)value;
                throw new Exception("Marshaller ToJS from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } not supported.");
            }
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "ondataavailable", __marshalledValue_3858);
        }
    }

    public Iskra.StdWeb.EventHandlerNonNull? Onpause
    {
        get
        {
            Iskra.StdWeb.EventHandlerNonNull? __res_3860;
            JSObject? __res_3861 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onpause");
            if (__res_3861 is null)
            {
                __res_3860 = null;
            }
            else
            {
                JSObject __notNullable_3862 = (JSObject)__res_3861;
                throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } not supported.");
            }
            return __res_3860;
        }
        set
        {
            JSObject? __marshalledValue_3863;
            if (value is null)
            {
                __marshalledValue_3863 = null;
            }
            else
            {
                Iskra.StdWeb.EventHandlerNonNull __notNullable_3864 = (Iskra.StdWeb.EventHandlerNonNull)value;
                throw new Exception("Marshaller ToJS from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } not supported.");
            }
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onpause", __marshalledValue_3863);
        }
    }

    public Iskra.StdWeb.EventHandlerNonNull? Onresume
    {
        get
        {
            Iskra.StdWeb.EventHandlerNonNull? __res_3865;
            JSObject? __res_3866 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onresume");
            if (__res_3866 is null)
            {
                __res_3865 = null;
            }
            else
            {
                JSObject __notNullable_3867 = (JSObject)__res_3866;
                throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } not supported.");
            }
            return __res_3865;
        }
        set
        {
            JSObject? __marshalledValue_3868;
            if (value is null)
            {
                __marshalledValue_3868 = null;
            }
            else
            {
                Iskra.StdWeb.EventHandlerNonNull __notNullable_3869 = (Iskra.StdWeb.EventHandlerNonNull)value;
                throw new Exception("Marshaller ToJS from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } not supported.");
            }
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onresume", __marshalledValue_3868);
        }
    }

    public Iskra.StdWeb.EventHandlerNonNull? Onerror
    {
        get
        {
            Iskra.StdWeb.EventHandlerNonNull? __res_3870;
            JSObject? __res_3871 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onerror");
            if (__res_3871 is null)
            {
                __res_3870 = null;
            }
            else
            {
                JSObject __notNullable_3872 = (JSObject)__res_3871;
                throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } not supported.");
            }
            return __res_3870;
        }
        set
        {
            JSObject? __marshalledValue_3873;
            if (value is null)
            {
                __marshalledValue_3873 = null;
            }
            else
            {
                Iskra.StdWeb.EventHandlerNonNull __notNullable_3874 = (Iskra.StdWeb.EventHandlerNonNull)value;
                throw new Exception("Marshaller ToJS from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } not supported.");
            }
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onerror", __marshalledValue_3873);
        }
    }

    public uint VideoBitsPerSecond
    {
        get
        {
            uint __res_3875;
            double __res_3876 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "videoBitsPerSecond");
            __res_3875 = Convert.ToUInt32(__res_3876);
            return __res_3875;
        }
    }

    public uint AudioBitsPerSecond
    {
        get
        {
            uint __res_3877;
            double __res_3878 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "audioBitsPerSecond");
            __res_3877 = Convert.ToUInt32(__res_3878);
            return __res_3877;
        }
    }

    public Iskra.StdWeb.BitrateMode AudioBitrateMode
    {
        get
        {
            Iskra.StdWeb.BitrateMode __res_3879;
            JSObject __res_3880 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "audioBitrateMode");
            throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = BitrateMode } not supported.");
            return __res_3879;
        }
    }
}

#nullable disable