// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class MediaMetadata(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public string Title
    {
        get
        {
            string __res_1397;
            string __res_1398 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "title");
            __res_1397 = __res_1398;
            return __res_1397;
        }
        set
        {
            string __marshalledValue_1399;
            __marshalledValue_1399 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "title", __marshalledValue_1399);
        }
    }

    public string Artist
    {
        get
        {
            string __res_1400;
            string __res_1401 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "artist");
            __res_1400 = __res_1401;
            return __res_1400;
        }
        set
        {
            string __marshalledValue_1402;
            __marshalledValue_1402 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "artist", __marshalledValue_1402);
        }
    }

    public string Album
    {
        get
        {
            string __res_1403;
            string __res_1404 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "album");
            __res_1403 = __res_1404;
            return __res_1403;
        }
        set
        {
            string __marshalledValue_1405;
            __marshalledValue_1405 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "album", __marshalledValue_1405);
        }
    }

    public global::Iskra.JSCore.Generics.FrozenArray<global::System.Runtime.InteropServices.JavaScript.JSObject, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement> Artwork
    {
        get
        {
            global::Iskra.JSCore.Generics.FrozenArray<global::System.Runtime.InteropServices.JavaScript.JSObject, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement> __res_1406;
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_1407;
            __propObject_1407 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "artwork");
            __res_1406 = new global::Iskra.JSCore.Generics.FrozenArray<global::System.Runtime.InteropServices.JavaScript.JSObject, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement>(__propObject_1407);
            return __res_1406;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_1408 = value.JSObject;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(JSObject, "artwork", __propObject_1408);
        }
    }

    public global::Iskra.JSCore.Generics.FrozenArray<global::Iskra.StdWeb.ChapterInformation, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement> ChapterInfo
    {
        get
        {
            global::Iskra.JSCore.Generics.FrozenArray<global::Iskra.StdWeb.ChapterInformation, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement> __res_1409;
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_1410;
            __propObject_1410 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "chapterInfo");
            __res_1409 = new global::Iskra.JSCore.Generics.FrozenArray<global::Iskra.StdWeb.ChapterInformation, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement>(__propObject_1410);
            return __res_1409;
        }
    }
}

#nullable disable