// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class MIDIPort(global::System.Runtime.InteropServices.JavaScript.JSObject obj): EventTarget(obj)
{
    public string Id
    {
        get
        {
            string __res_13349;
            string __res_13350 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "id");
            __res_13349 = __res_13350;
            return __res_13349;
        }
    }

    public string? Manufacturer
    {
        get
        {
            string? __res_13351;
            string? __res_13352 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2AsNullable(JSObject, "manufacturer");
            if (__res_13352 is null)
            {
                __res_13351 = null;
            }
            else
            {
                string __notNullable_13353 = (string)__res_13352;
                __res_13351 = __notNullable_13353;
            }
            return __res_13351;
        }
    }

    public string? Name
    {
        get
        {
            string? __res_13354;
            string? __res_13355 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2AsNullable(JSObject, "name");
            if (__res_13355 is null)
            {
                __res_13354 = null;
            }
            else
            {
                string __notNullable_13356 = (string)__res_13355;
                __res_13354 = __notNullable_13356;
            }
            return __res_13354;
        }
    }

    public global::Iskra.StdWeb.MIDIPortType Type
    {
        get
        {
            global::Iskra.StdWeb.MIDIPortType __res_13357;
            string __res_13358 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "type");
            __res_13357 = global::Iskra.StdWeb.MIDIPortType.Create(__res_13358);
            return __res_13357;
        }
    }

    public string? Version
    {
        get
        {
            string? __res_13359;
            string? __res_13360 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2AsNullable(JSObject, "version");
            if (__res_13360 is null)
            {
                __res_13359 = null;
            }
            else
            {
                string __notNullable_13361 = (string)__res_13360;
                __res_13359 = __notNullable_13361;
            }
            return __res_13359;
        }
    }

    public global::Iskra.StdWeb.MIDIPortDeviceState State
    {
        get
        {
            global::Iskra.StdWeb.MIDIPortDeviceState __res_13362;
            string __res_13363 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "state");
            __res_13362 = global::Iskra.StdWeb.MIDIPortDeviceState.Create(__res_13363);
            return __res_13362;
        }
    }

    public global::Iskra.StdWeb.MIDIPortConnectionState Connection
    {
        get
        {
            global::Iskra.StdWeb.MIDIPortConnectionState __res_13364;
            string __res_13365 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "connection");
            __res_13364 = global::Iskra.StdWeb.MIDIPortConnectionState.Create(__res_13365);
            return __res_13364;
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onstatechange
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_13366;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_13367 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onstatechange");
            if (__res_13367 is null)
            {
                __res_13366 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_13368 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_13367;
                __res_13366 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_13368);
            }
            return __res_13366;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_13369;
            if (value is null)
            {
                __marshalledValue_13369 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_13370 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_13369 = __notNullable_13370.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onstatechange", __marshalledValue_13369);
        }
    }
}

#nullable disable