// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public delegate global::Iskra.JSCore.Promise NavigationInterceptHandlerManaged();

public partial class NavigationInterceptHandler(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public static implicit operator NavigationInterceptHandler(NavigationInterceptHandlerManaged input)
    {
        Action<global::System.Runtime.InteropServices.JavaScript.JSObject, global::System.Runtime.InteropServices.JavaScript.JSObject> callback = (__args_281, __res_284) =>
        {
            using (__args_281)
            using (__res_284)
            {


                global::Iskra.JSCore.Promise __managedRes_285 = input();

                global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_286 = __managedRes_285.JSObject;
                global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(__res_284, "value", __propObject_286);
            }
        };

        global::System.Runtime.InteropServices.JavaScript.JSObject __funcObj_283 = global::Iskra.JSCore.Extensions.JSFunctionExtensions.WrapAsNonVoidFunction(callback);
        global::Iskra.JSCore.Extensions.JSFunctionExtensions.StoreManagedFunctionToProperty(__funcObj_283, input); 

        return new global::Iskra.StdWeb.NavigationInterceptHandler(__funcObj_283);
    }

    public bool TryGetManaged([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] out global::Iskra.StdWeb.NavigationInterceptHandlerManaged? managed, bool allowConversion = false)
    {
        managed = global::Iskra.JSCore.Extensions.JSFunctionExtensions.GetManagedFunctionFromProperty(JSObject) as global::Iskra.StdWeb.NavigationInterceptHandlerManaged;
        if (managed is not null)
        {
            return true;
        }

        if (!allowConversion)
        {
            return false;
        }

        managed = () =>
        {


            using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_288 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

            global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallEmptyNonVoidFunction(JSObject, null, __resOwner_288.JSObject);

            // Return Value
            global::Iskra.JSCore.Promise __res_289;
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_290;
            __propObject_290 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(__resOwner_288.JSObject, "value");
            __res_289 = new global::Iskra.JSCore.Promise(__propObject_290);
            return __res_289;
        };
        return true;
    }
}

#nullable disable