// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class Navigation(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.StdWeb.EventTarget(obj)
{
    public global::Iskra.JSCore.Generics.JSArray<global::Iskra.StdWeb.NavigationHistoryEntry, global::Iskra.StdWeb.PropertyAccessor> Entries()
    {


        using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_1323 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

        global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallEmptyNonVoidFunctionProperty(JSObject, "entries", JSObject, __resOwner_1323.JSObject);

        // Return Value
        return global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.JSCore.Generics.JSArray<global::Iskra.StdWeb.NavigationHistoryEntry, global::Iskra.StdWeb.PropertyAccessor>, global::Iskra.StdWeb.PropertyAccessor>(__resOwner_1323.JSObject, "value");
    }

    public global::Iskra.StdWeb.NavigationHistoryEntry? CurrentEntry
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.NavigationHistoryEntry?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "currentEntry");
    }

    public void UpdateCurrentEntry(global::Iskra.StdWeb.NavigationUpdateCurrentEntryOptions options)
    {
        int ___argsArrayLength_0 = 1;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_1325 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        global::System.Runtime.InteropServices.JavaScript.JSObject ___marshalledValue_1;
        ___marshalledValue_1 = options.JSObject;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(__argsArray_1325.JSObject, 0, ___marshalledValue_1);

        global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallNonEmptyVoidFunctionProperty(JSObject, "updateCurrentEntry", JSObject, __argsArray_1325.JSObject);
    }

    public global::Iskra.StdWeb.NavigationTransition? Transition
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.NavigationTransition?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "transition");
    }

    public global::Iskra.StdWeb.NavigationActivation? Activation
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.NavigationActivation?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "activation");
    }

    public bool CanGoBack
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<bool, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "canGoBack");
    }

    public bool CanGoForward
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<bool, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "canGoForward");
    }

    public global::Iskra.StdWeb.NavigationResult Navigate(string url)
    {
        int ___argsArrayLength_0 = 1;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_1331 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        string ___marshalledValue_1;
        ___marshalledValue_1 = url;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(__argsArray_1331.JSObject, 0, ___marshalledValue_1);

        using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_1332 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

        global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallNonEmptyNonVoidFunctionProperty(JSObject, "navigate", JSObject, __argsArray_1331.JSObject, __resOwner_1332.JSObject);

        // Return Value
        return global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.NavigationResult, global::Iskra.StdWeb.PropertyAccessor>(__resOwner_1332.JSObject, "value");
    }

    public global::Iskra.StdWeb.NavigationResult Navigate(string url, global::Iskra.StdWeb.NavigationNavigateOptions options)
    {
        int ___argsArrayLength_0 = 2;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_1328 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        string ___marshalledValue_1;
        ___marshalledValue_1 = url;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(__argsArray_1328.JSObject, 0, ___marshalledValue_1);

        // Argument 2
        global::System.Runtime.InteropServices.JavaScript.JSObject ___marshalledValue_2;
        ___marshalledValue_2 = options.JSObject;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(__argsArray_1328.JSObject, 1, ___marshalledValue_2);

        using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_1329 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

        global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallNonEmptyNonVoidFunctionProperty(JSObject, "navigate", JSObject, __argsArray_1328.JSObject, __resOwner_1329.JSObject);

        // Return Value
        return global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.NavigationResult, global::Iskra.StdWeb.PropertyAccessor>(__resOwner_1329.JSObject, "value");
    }

    public global::Iskra.StdWeb.NavigationResult Reload()
    {


        using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_1338 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

        global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallEmptyNonVoidFunctionProperty(JSObject, "reload", JSObject, __resOwner_1338.JSObject);

        // Return Value
        return global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.NavigationResult, global::Iskra.StdWeb.PropertyAccessor>(__resOwner_1338.JSObject, "value");
    }

    public global::Iskra.StdWeb.NavigationResult Reload(global::Iskra.StdWeb.NavigationReloadOptions options)
    {
        int ___argsArrayLength_0 = 1;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_1334 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        global::System.Runtime.InteropServices.JavaScript.JSObject ___marshalledValue_1;
        ___marshalledValue_1 = options.JSObject;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(__argsArray_1334.JSObject, 0, ___marshalledValue_1);

        using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_1335 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

        global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallNonEmptyNonVoidFunctionProperty(JSObject, "reload", JSObject, __argsArray_1334.JSObject, __resOwner_1335.JSObject);

        // Return Value
        return global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.NavigationResult, global::Iskra.StdWeb.PropertyAccessor>(__resOwner_1335.JSObject, "value");
    }

    public global::Iskra.StdWeb.NavigationResult TraverseTo(string key)
    {
        int ___argsArrayLength_0 = 1;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_1343 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        string ___marshalledValue_1;
        ___marshalledValue_1 = key;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(__argsArray_1343.JSObject, 0, ___marshalledValue_1);

        using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_1344 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

        global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallNonEmptyNonVoidFunctionProperty(JSObject, "traverseTo", JSObject, __argsArray_1343.JSObject, __resOwner_1344.JSObject);

        // Return Value
        return global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.NavigationResult, global::Iskra.StdWeb.PropertyAccessor>(__resOwner_1344.JSObject, "value");
    }

    public global::Iskra.StdWeb.NavigationResult TraverseTo(string key, global::Iskra.StdWeb.NavigationOptions options)
    {
        int ___argsArrayLength_0 = 2;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_1340 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        string ___marshalledValue_1;
        ___marshalledValue_1 = key;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(__argsArray_1340.JSObject, 0, ___marshalledValue_1);

        // Argument 2
        global::System.Runtime.InteropServices.JavaScript.JSObject ___marshalledValue_2;
        ___marshalledValue_2 = options.JSObject;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(__argsArray_1340.JSObject, 1, ___marshalledValue_2);

        using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_1341 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

        global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallNonEmptyNonVoidFunctionProperty(JSObject, "traverseTo", JSObject, __argsArray_1340.JSObject, __resOwner_1341.JSObject);

        // Return Value
        return global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.NavigationResult, global::Iskra.StdWeb.PropertyAccessor>(__resOwner_1341.JSObject, "value");
    }

    public global::Iskra.StdWeb.NavigationResult Back()
    {


        using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_1350 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

        global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallEmptyNonVoidFunctionProperty(JSObject, "back", JSObject, __resOwner_1350.JSObject);

        // Return Value
        return global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.NavigationResult, global::Iskra.StdWeb.PropertyAccessor>(__resOwner_1350.JSObject, "value");
    }

    public global::Iskra.StdWeb.NavigationResult Back(global::Iskra.StdWeb.NavigationOptions options)
    {
        int ___argsArrayLength_0 = 1;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_1346 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        global::System.Runtime.InteropServices.JavaScript.JSObject ___marshalledValue_1;
        ___marshalledValue_1 = options.JSObject;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(__argsArray_1346.JSObject, 0, ___marshalledValue_1);

        using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_1347 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

        global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallNonEmptyNonVoidFunctionProperty(JSObject, "back", JSObject, __argsArray_1346.JSObject, __resOwner_1347.JSObject);

        // Return Value
        return global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.NavigationResult, global::Iskra.StdWeb.PropertyAccessor>(__resOwner_1347.JSObject, "value");
    }

    public global::Iskra.StdWeb.NavigationResult Forward()
    {


        using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_1356 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

        global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallEmptyNonVoidFunctionProperty(JSObject, "forward", JSObject, __resOwner_1356.JSObject);

        // Return Value
        return global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.NavigationResult, global::Iskra.StdWeb.PropertyAccessor>(__resOwner_1356.JSObject, "value");
    }

    public global::Iskra.StdWeb.NavigationResult Forward(global::Iskra.StdWeb.NavigationOptions options)
    {
        int ___argsArrayLength_0 = 1;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_1352 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        global::System.Runtime.InteropServices.JavaScript.JSObject ___marshalledValue_1;
        ___marshalledValue_1 = options.JSObject;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(__argsArray_1352.JSObject, 0, ___marshalledValue_1);

        using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_1353 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

        global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallNonEmptyNonVoidFunctionProperty(JSObject, "forward", JSObject, __argsArray_1352.JSObject, __resOwner_1353.JSObject);

        // Return Value
        return global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.NavigationResult, global::Iskra.StdWeb.PropertyAccessor>(__resOwner_1353.JSObject, "value");
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onnavigate
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onnavigate");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onnavigate", value);
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onnavigatesuccess
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onnavigatesuccess");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onnavigatesuccess", value);
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onnavigateerror
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onnavigateerror");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onnavigateerror", value);
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Oncurrententrychange
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "oncurrententrychange");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "oncurrententrychange", value);
    }
}

#nullable disable