// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class NetworkInformation(JSObject obj): EventTarget(obj)
{
    public ConnectionType Type
    {
        get
        {
            throw new Exception();
        }
    }

    public EffectiveConnectionType EffectiveType
    {
        get
        {
            throw new Exception();
        }
    }

    public Megabit DownlinkMax
    {
        get
        {
            throw new Exception();
        }
    }

    public Megabit Downlink
    {
        get
        {
            throw new Exception();
        }
    }

    public Millisecond Rtt
    {
        get
        {
            throw new Exception();
        }
    }

    public EventHandler Onchange
    {
        get
        {
            throw new Exception();
        }
        set
        {
            throw new Exception();
        }
    }
}

#nullable disable