// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class NotRestoredReasonDetails(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public string Reason
    {
        get
        {
            string __res_7852;
            string __res_7853 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "reason");
            __res_7852 = __res_7853;
            return __res_7852;
        }
    }
}

#nullable disable