// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class OffscreenCanvas(global::System.Runtime.InteropServices.JavaScript.JSObject obj): EventTarget(obj)
{
    public ulong Width
    {
        get
        {
            ulong __res_6530;
            double __res_6531 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "width");
            __res_6530 = Convert.ToUInt64(__res_6531);
            return __res_6530;
        }
        set
        {
            double __marshalledValue_6532;
            __marshalledValue_6532 = Convert.ToDouble(value);
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "width", __marshalledValue_6532);
        }
    }

    public ulong Height
    {
        get
        {
            ulong __res_6533;
            double __res_6534 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "height");
            __res_6533 = Convert.ToUInt64(__res_6534);
            return __res_6533;
        }
        set
        {
            double __marshalledValue_6535;
            __marshalledValue_6535 = Convert.ToDouble(value);
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "height", __marshalledValue_6535);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Oncontextlost
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6536;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6537 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "oncontextlost");
            if (__res_6537 is null)
            {
                __res_6536 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6538 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6537;
                throw new global::System.Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } not supported.");
            }
            return __res_6536;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6539;
            if (value is null)
            {
                __marshalledValue_6539 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6540 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                throw new global::System.Exception("Marshaller ToJS from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } not supported.");
            }
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "oncontextlost", __marshalledValue_6539);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Oncontextrestored
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6541;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6542 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "oncontextrestored");
            if (__res_6542 is null)
            {
                __res_6541 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6543 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6542;
                throw new global::System.Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } not supported.");
            }
            return __res_6541;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6544;
            if (value is null)
            {
                __marshalledValue_6544 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6545 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                throw new global::System.Exception("Marshaller ToJS from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } not supported.");
            }
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "oncontextrestored", __marshalledValue_6544);
        }
    }
}

#nullable disable