// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public sealed partial class OrientationSensorLocalCoordinateSystem
{
    private readonly string _value;

    private OrientationSensorLocalCoordinateSystem(string value)
    {
        _value = value;
    }

    public static readonly OrientationSensorLocalCoordinateSystem Device = new("device");
    public static readonly OrientationSensorLocalCoordinateSystem Screen = new("screen");

    public override string ToString() => _value;

    public static OrientationSensorLocalCoordinateSystem Create(string value) => value switch
    {
        "device" => Device,
        "screen" => Screen,
        _ => throw new ArgumentException($"Invalid value \"{value}\" for OrientationSensorLocalCoordinateSystem", nameof(value)),
    };
}

#nullable disable