// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class PageRevealEvent(JSObject obj): Event(obj)
{
    public Iskra.StdWeb.ViewTransition? ViewTransition
    {
        get
        {
            Iskra.StdWeb.ViewTransition? __res_6764;
            JSObject? __res_6765 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "viewTransition");
            if (__res_6765 is null)
            {
                __res_6764 = null;
            }
            else
            {
                JSObject __notNullable_6766 = (JSObject)__res_6765;
                throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = ViewTransition } not supported.");
            }
            return __res_6764;
        }
    }
}

#nullable disable