// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class PerformanceLongAnimationFrameTiming(global::System.Runtime.InteropServices.JavaScript.JSObject obj): PerformanceEntry(obj)
{
    public new double StartTime
    {
        get
        {
            double __res_12776;
            double __res_12777 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "startTime");
            __res_12776 = __res_12777;
            return __res_12776;
        }
    }

    public new double Duration
    {
        get
        {
            double __res_12778;
            double __res_12779 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "duration");
            __res_12778 = __res_12779;
            return __res_12778;
        }
    }

    public new string Name
    {
        get
        {
            string __res_12780;
            string __res_12781 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "name");
            __res_12780 = __res_12781;
            return __res_12780;
        }
    }

    public new string EntryType
    {
        get
        {
            string __res_12782;
            string __res_12783 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "entryType");
            __res_12782 = __res_12783;
            return __res_12782;
        }
    }

    public double RenderStart
    {
        get
        {
            double __res_12784;
            double __res_12785 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "renderStart");
            __res_12784 = __res_12785;
            return __res_12784;
        }
    }

    public double StyleAndLayoutStart
    {
        get
        {
            double __res_12786;
            double __res_12787 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "styleAndLayoutStart");
            __res_12786 = __res_12787;
            return __res_12786;
        }
    }

    public double BlockingDuration
    {
        get
        {
            double __res_12788;
            double __res_12789 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "blockingDuration");
            __res_12788 = __res_12789;
            return __res_12788;
        }
    }

    public double FirstUIEventTimestamp
    {
        get
        {
            double __res_12790;
            double __res_12791 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "firstUIEventTimestamp");
            __res_12790 = __res_12791;
            return __res_12790;
        }
    }

    public global::Iskra.JSCore.Generics.FrozenArray<global::Iskra.StdWeb.PerformanceScriptTiming, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement> Scripts
    {
        get
        {
            global::Iskra.JSCore.Generics.FrozenArray<global::Iskra.StdWeb.PerformanceScriptTiming, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement> __res_12792;
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_12793;
            __propObject_12793 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "scripts");
            __res_12792 = new global::Iskra.JSCore.Generics.FrozenArray<global::Iskra.StdWeb.PerformanceScriptTiming, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement>(__propObject_12793);
            return __res_12792;
        }
    }

    public double PaintTime
    {
        get
        {
            double __res_12794;
            double __res_12795 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "paintTime");
            __res_12794 = __res_12795;
            return __res_12794;
        }
    }

    public double? PresentationTime
    {
        get
        {
            double? __res_12796;
            double? __res_12797 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2AsNullable(JSObject, "presentationTime");
            if (__res_12797 is null)
            {
                __res_12796 = null;
            }
            else
            {
                double __notNullable_12798 = (double)__res_12797;
                __res_12796 = __notNullable_12798;
            }
            return __res_12796;
        }
    }
}

#nullable disable