// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class PerformanceScriptTiming(JSObject obj): PerformanceEntry(obj)
{
    public double StartTime
    {
        get
        {
            double __res_5935;
            double __res_5936 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "startTime");
            __res_5935 = __res_5936;
            return __res_5935;
        }
    }

    public double Duration
    {
        get
        {
            double __res_5937;
            double __res_5938 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "duration");
            __res_5937 = __res_5938;
            return __res_5937;
        }
    }

    public string Name
    {
        get
        {
            string __res_5939;
            string __res_5940 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "name");
            __res_5939 = __res_5940;
            return __res_5939;
        }
    }

    public string EntryType
    {
        get
        {
            string __res_5941;
            string __res_5942 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "entryType");
            __res_5941 = __res_5942;
            return __res_5941;
        }
    }

    public Iskra.StdWeb.ScriptInvokerType InvokerType
    {
        get
        {
            Iskra.StdWeb.ScriptInvokerType __res_5943;
            JSObject __res_5944 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "invokerType");
            throw new Exception("Marshaller from \"__res_5944\" to \"__res_5943\" not supported.");
            return __res_5943;
        }
    }

    public string Invoker
    {
        get
        {
            string __res_5945;
            string __res_5946 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "invoker");
            __res_5945 = __res_5946;
            return __res_5945;
        }
    }

    public double ExecutionStart
    {
        get
        {
            double __res_5947;
            double __res_5948 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "executionStart");
            __res_5947 = __res_5948;
            return __res_5947;
        }
    }

    public string SourceURL
    {
        get
        {
            string __res_5949;
            string __res_5950 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "sourceURL");
            __res_5949 = __res_5950;
            return __res_5949;
        }
    }

    public string SourceFunctionName
    {
        get
        {
            string __res_5951;
            string __res_5952 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "sourceFunctionName");
            __res_5951 = __res_5952;
            return __res_5951;
        }
    }

    public long SourceCharPosition
    {
        get
        {
            long __res_5953;
            double __res_5954 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "sourceCharPosition");
            __res_5953 = Convert.ToInt64(__res_5954);
            return __res_5953;
        }
    }

    public double PauseDuration
    {
        get
        {
            double __res_5955;
            double __res_5956 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "pauseDuration");
            __res_5955 = __res_5956;
            return __res_5955;
        }
    }

    public double ForcedStyleAndLayoutDuration
    {
        get
        {
            double __res_5957;
            double __res_5958 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "forcedStyleAndLayoutDuration");
            __res_5957 = __res_5958;
            return __res_5957;
        }
    }

    public Iskra.StdWeb.Window? Window
    {
        get
        {
            Iskra.StdWeb.Window? __res_5959;
            JSObject? __res_5960 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "window");
            if (__res_5960 is null)
            {
                __res_5959 = null;
            }
            else
            {
                JSObject __notNullable_5961 = (JSObject)__res_5960;
                throw new Exception("Marshaller from \"__notNullable_5961\" to \"__res_5959\" not supported.");
            }
            return __res_5959;
        }
    }

    public Iskra.StdWeb.ScriptWindowAttribution WindowAttribution
    {
        get
        {
            Iskra.StdWeb.ScriptWindowAttribution __res_5962;
            JSObject __res_5963 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "windowAttribution");
            throw new Exception("Marshaller from \"__res_5963\" to \"__res_5962\" not supported.");
            return __res_5962;
        }
    }
}

#nullable disable