// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class QuotaExceededError(global::System.Runtime.InteropServices.JavaScript.JSObject obj): DOMException(obj)
{
    public double? Quota
    {
        get
        {
            double? __res_5890;
            double? __res_5891 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2AsNullable(JSObject, "quota");
            if (__res_5891 is null)
            {
                __res_5890 = null;
            }
            else
            {
                double __notNullable_5892 = (double)__res_5891;
                __res_5890 = __notNullable_5892;
            }
            return __res_5890;
        }
    }

    public double? Requested
    {
        get
        {
            double? __res_5893;
            double? __res_5894 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2AsNullable(JSObject, "requested");
            if (__res_5894 is null)
            {
                __res_5893 = null;
            }
            else
            {
                double __notNullable_5895 = (double)__res_5894;
                __res_5893 = __notNullable_5895;
            }
            return __res_5893;
        }
    }
}

#nullable disable