// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class RTCError(global::System.Runtime.InteropServices.JavaScript.JSObject obj): DOMException(obj)
{
    public global::Iskra.StdWeb.RTCErrorDetailType ErrorDetail
    {
        get
        {
            global::Iskra.StdWeb.RTCErrorDetailType __res_2074;
            string __res_2075 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "errorDetail");
            __res_2074 = global::Iskra.StdWeb.RTCErrorDetailType.Create(__res_2075);
            return __res_2074;
        }
    }

    public int? SdpLineNumber
    {
        get
        {
            int? __res_2076;
            double? __res_2077 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2AsNullable(JSObject, "sdpLineNumber");
            if (__res_2077 is null)
            {
                __res_2076 = null;
            }
            else
            {
                double __notNullable_2078 = (double)__res_2077;
                __res_2076 = Convert.ToInt32(__notNullable_2078);
            }
            return __res_2076;
        }
    }

    public int? SctpCauseCode
    {
        get
        {
            int? __res_2079;
            double? __res_2080 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2AsNullable(JSObject, "sctpCauseCode");
            if (__res_2080 is null)
            {
                __res_2079 = null;
            }
            else
            {
                double __notNullable_2081 = (double)__res_2080;
                __res_2079 = Convert.ToInt32(__notNullable_2081);
            }
            return __res_2079;
        }
    }

    public uint? ReceivedAlert
    {
        get
        {
            uint? __res_2082;
            double? __res_2083 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2AsNullable(JSObject, "receivedAlert");
            if (__res_2083 is null)
            {
                __res_2082 = null;
            }
            else
            {
                double __notNullable_2084 = (double)__res_2083;
                __res_2082 = Convert.ToUInt32(__notNullable_2084);
            }
            return __res_2082;
        }
    }

    public uint? SentAlert
    {
        get
        {
            uint? __res_2085;
            double? __res_2086 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2AsNullable(JSObject, "sentAlert");
            if (__res_2086 is null)
            {
                __res_2085 = null;
            }
            else
            {
                double __notNullable_2087 = (double)__res_2086;
                __res_2085 = Convert.ToUInt32(__notNullable_2087);
            }
            return __res_2085;
        }
    }
}

#nullable disable