// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public sealed partial class ScrollRestoration
{
    private readonly string _value;

    private ScrollRestoration(string value)
    {
        _value = value;
    }

    public static readonly ScrollRestoration Auto = new("auto");
    public static readonly ScrollRestoration Manual = new("manual");

    public override string ToString() => _value;

    public static ScrollRestoration Create(string value) => value switch
    {
        "auto" => Auto,
        "manual" => Manual,
        _ => throw new ArgumentException($"Invalid value \"{value}\" for ScrollRestoration", nameof(value)),
    };
}

#nullable disable