// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class ServiceWorker(global::System.Runtime.InteropServices.JavaScript.JSObject obj): EventTarget(obj)
{
    public string ScriptURL
    {
        get
        {
            string __res_4525;
            string __res_4526 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "scriptURL");
            __res_4525 = __res_4526;
            return __res_4525;
        }
    }

    public global::Iskra.StdWeb.ServiceWorkerState State
    {
        get
        {
            global::Iskra.StdWeb.ServiceWorkerState __res_4527;
            string __res_4528 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "state");
            __res_4527 = global::Iskra.StdWeb.ServiceWorkerState.Create(__res_4528);
            return __res_4527;
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onstatechange
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_4529;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_4530 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onstatechange");
            if (__res_4530 is null)
            {
                __res_4529 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_4531 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_4530;
                throw new global::System.Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } not supported.");
            }
            return __res_4529;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_4532;
            if (value is null)
            {
                __marshalledValue_4532 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_4533 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                throw new global::System.Exception("Marshaller ToJS from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } not supported.");
            }
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onstatechange", __marshalledValue_4532);
        }
    }
}

#nullable disable