// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class SharedStorageWorkletGlobalScope(global::System.Runtime.InteropServices.JavaScript.JSObject obj): WorkletGlobalScope(obj)
{
    public global::Iskra.StdWeb.SharedStorage SharedStorage
    {
        get
        {
            global::Iskra.StdWeb.SharedStorage __res_4177;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_4178 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "sharedStorage");
            __res_4177 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SharedStorage>(__res_4178);
            return __res_4177;
        }
    }

    public global::Iskra.StdWeb.PrivateAggregation PrivateAggregation
    {
        get
        {
            global::Iskra.StdWeb.PrivateAggregation __res_4179;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_4180 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "privateAggregation");
            __res_4179 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.PrivateAggregation>(__res_4180);
            return __res_4179;
        }
    }

    public global::Iskra.StdWeb.SharedStorageWorkletNavigator Navigator
    {
        get
        {
            global::Iskra.StdWeb.SharedStorageWorkletNavigator __res_4181;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_4182 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "navigator");
            __res_4181 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SharedStorageWorkletNavigator>(__res_4182);
            return __res_4181;
        }
    }
}

#nullable disable