// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class SharedStorageWorkletGlobalScope(global::System.Runtime.InteropServices.JavaScript.JSObject obj): WorkletGlobalScope(obj)
{
    public global::Iskra.StdWeb.SharedStorage SharedStorage
    {
        get
        {
            global::Iskra.StdWeb.SharedStorage __res_6860;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_6861 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "sharedStorage");
            __res_6860 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SharedStorage>(__res_6861);
            return __res_6860;
        }
    }

    public global::Iskra.StdWeb.PrivateAggregation PrivateAggregation
    {
        get
        {
            global::Iskra.StdWeb.PrivateAggregation __res_6862;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_6863 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "privateAggregation");
            __res_6862 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.PrivateAggregation>(__res_6863);
            return __res_6862;
        }
    }

    public global::Iskra.StdWeb.SharedStorageWorkletNavigator Navigator
    {
        get
        {
            global::Iskra.StdWeb.SharedStorageWorkletNavigator __res_6864;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_6865 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "navigator");
            __res_6864 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SharedStorageWorkletNavigator>(__res_6865);
            return __res_6864;
        }
    }
}

#nullable disable