// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class SpeechSynthesisUtterance(global::System.Runtime.InteropServices.JavaScript.JSObject obj): EventTarget(obj)
{
    public string Text
    {
        get
        {
            string __res_6810;
            string __res_6811 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "text");
            __res_6810 = __res_6811;
            return __res_6810;
        }
        set
        {
            string __marshalledValue_6812;
            __marshalledValue_6812 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "text", __marshalledValue_6812);
        }
    }

    public string Lang
    {
        get
        {
            string __res_6813;
            string __res_6814 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "lang");
            __res_6813 = __res_6814;
            return __res_6813;
        }
        set
        {
            string __marshalledValue_6815;
            __marshalledValue_6815 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "lang", __marshalledValue_6815);
        }
    }

    public global::Iskra.StdWeb.SpeechSynthesisVoice? Voice
    {
        get
        {
            global::Iskra.StdWeb.SpeechSynthesisVoice? __res_6816;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6817 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "voice");
            if (__res_6817 is null)
            {
                __res_6816 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6818 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6817;
                __res_6816 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SpeechSynthesisVoice>(__notNullable_6818);
            }
            return __res_6816;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6819;
            if (value is null)
            {
                __marshalledValue_6819 = null;
            }
            else
            {
                global::Iskra.StdWeb.SpeechSynthesisVoice __notNullable_6820 = (global::Iskra.StdWeb.SpeechSynthesisVoice)value;
                __marshalledValue_6819 = __notNullable_6820.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "voice", __marshalledValue_6819);
        }
    }

    public float Volume
    {
        get
        {
            float __res_6821;
            double __res_6822 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "volume");
            __res_6821 = Convert.ToSingle(__res_6822);
            return __res_6821;
        }
        set
        {
            double __marshalledValue_6823;
            __marshalledValue_6823 = Convert.ToDouble(value);
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "volume", __marshalledValue_6823);
        }
    }

    public float Rate
    {
        get
        {
            float __res_6824;
            double __res_6825 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "rate");
            __res_6824 = Convert.ToSingle(__res_6825);
            return __res_6824;
        }
        set
        {
            double __marshalledValue_6826;
            __marshalledValue_6826 = Convert.ToDouble(value);
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "rate", __marshalledValue_6826);
        }
    }

    public float Pitch
    {
        get
        {
            float __res_6827;
            double __res_6828 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "pitch");
            __res_6827 = Convert.ToSingle(__res_6828);
            return __res_6827;
        }
        set
        {
            double __marshalledValue_6829;
            __marshalledValue_6829 = Convert.ToDouble(value);
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "pitch", __marshalledValue_6829);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onstart
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6830;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6831 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onstart");
            if (__res_6831 is null)
            {
                __res_6830 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6832 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6831;
                __res_6830 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6832);
            }
            return __res_6830;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6833;
            if (value is null)
            {
                __marshalledValue_6833 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6834 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6833 = __notNullable_6834.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onstart", __marshalledValue_6833);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onend
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6835;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6836 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onend");
            if (__res_6836 is null)
            {
                __res_6835 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6837 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6836;
                __res_6835 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6837);
            }
            return __res_6835;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6838;
            if (value is null)
            {
                __marshalledValue_6838 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6839 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6838 = __notNullable_6839.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onend", __marshalledValue_6838);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onerror
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6840;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6841 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onerror");
            if (__res_6841 is null)
            {
                __res_6840 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6842 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6841;
                __res_6840 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6842);
            }
            return __res_6840;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6843;
            if (value is null)
            {
                __marshalledValue_6843 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6844 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6843 = __notNullable_6844.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onerror", __marshalledValue_6843);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onpause
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6845;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6846 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onpause");
            if (__res_6846 is null)
            {
                __res_6845 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6847 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6846;
                __res_6845 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6847);
            }
            return __res_6845;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6848;
            if (value is null)
            {
                __marshalledValue_6848 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6849 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6848 = __notNullable_6849.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onpause", __marshalledValue_6848);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onresume
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6850;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6851 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onresume");
            if (__res_6851 is null)
            {
                __res_6850 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6852 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6851;
                __res_6850 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6852);
            }
            return __res_6850;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6853;
            if (value is null)
            {
                __marshalledValue_6853 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6854 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6853 = __notNullable_6854.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onresume", __marshalledValue_6853);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onmark
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6855;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6856 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onmark");
            if (__res_6856 is null)
            {
                __res_6855 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6857 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6856;
                __res_6855 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6857);
            }
            return __res_6855;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6858;
            if (value is null)
            {
                __marshalledValue_6858 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6859 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6858 = __notNullable_6859.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onmark", __marshalledValue_6858);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onboundary
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6860;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6861 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onboundary");
            if (__res_6861 is null)
            {
                __res_6860 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6862 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6861;
                __res_6860 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6862);
            }
            return __res_6860;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6863;
            if (value is null)
            {
                __marshalledValue_6863 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6864 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6863 = __notNullable_6864.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onboundary", __marshalledValue_6863);
        }
    }
}

#nullable disable