// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class SpeechRecognition(global::System.Runtime.InteropServices.JavaScript.JSObject obj): EventTarget(obj)
{
    public global::Iskra.StdWeb.SpeechGrammarList Grammars
    {
        get
        {
            global::Iskra.StdWeb.SpeechGrammarList __res_6636;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_6637 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "grammars");
            __res_6636 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SpeechGrammarList>(__res_6637);
            return __res_6636;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject __marshalledValue_6638;
            __marshalledValue_6638 = value.JSObject;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(JSObject, "grammars", __marshalledValue_6638);
        }
    }

    public string Lang
    {
        get
        {
            string __res_6639;
            string __res_6640 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "lang");
            __res_6639 = __res_6640;
            return __res_6639;
        }
        set
        {
            string __marshalledValue_6641;
            __marshalledValue_6641 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "lang", __marshalledValue_6641);
        }
    }

    public bool Continuous
    {
        get
        {
            bool __res_6642;
            bool __res_6643 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "continuous");
            __res_6642 = __res_6643;
            return __res_6642;
        }
        set
        {
            bool __marshalledValue_6644;
            __marshalledValue_6644 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "continuous", __marshalledValue_6644);
        }
    }

    public bool InterimResults
    {
        get
        {
            bool __res_6645;
            bool __res_6646 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "interimResults");
            __res_6645 = __res_6646;
            return __res_6645;
        }
        set
        {
            bool __marshalledValue_6647;
            __marshalledValue_6647 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "interimResults", __marshalledValue_6647);
        }
    }

    public uint MaxAlternatives
    {
        get
        {
            uint __res_6648;
            double __res_6649 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "maxAlternatives");
            __res_6648 = Convert.ToUInt32(__res_6649);
            return __res_6648;
        }
        set
        {
            double __marshalledValue_6650;
            __marshalledValue_6650 = Convert.ToDouble(value);
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "maxAlternatives", __marshalledValue_6650);
        }
    }

    public bool ProcessLocally
    {
        get
        {
            bool __res_6651;
            bool __res_6652 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "processLocally");
            __res_6651 = __res_6652;
            return __res_6651;
        }
        set
        {
            bool __marshalledValue_6653;
            __marshalledValue_6653 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "processLocally", __marshalledValue_6653);
        }
    }

    public global::Iskra.JSCore.Generics.ObservableArray<global::Iskra.StdWeb.SpeechRecognitionPhrase, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement> Phrases
    {
        get
        {
            global::Iskra.JSCore.Generics.ObservableArray<global::Iskra.StdWeb.SpeechRecognitionPhrase, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement> __res_6654;
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_6655;
            __propObject_6655 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "phrases");
            __res_6654 = new global::Iskra.JSCore.Generics.ObservableArray<global::Iskra.StdWeb.SpeechRecognitionPhrase, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement>(__propObject_6655);
            return __res_6654;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_6656 = value.JSObject;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(JSObject, "phrases", __propObject_6656);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onaudiostart
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6657;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6658 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onaudiostart");
            if (__res_6658 is null)
            {
                __res_6657 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6659 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6658;
                __res_6657 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6659);
            }
            return __res_6657;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6660;
            if (value is null)
            {
                __marshalledValue_6660 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6661 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6660 = __notNullable_6661.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onaudiostart", __marshalledValue_6660);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onsoundstart
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6662;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6663 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onsoundstart");
            if (__res_6663 is null)
            {
                __res_6662 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6664 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6663;
                __res_6662 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6664);
            }
            return __res_6662;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6665;
            if (value is null)
            {
                __marshalledValue_6665 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6666 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6665 = __notNullable_6666.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onsoundstart", __marshalledValue_6665);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onspeechstart
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6667;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6668 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onspeechstart");
            if (__res_6668 is null)
            {
                __res_6667 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6669 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6668;
                __res_6667 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6669);
            }
            return __res_6667;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6670;
            if (value is null)
            {
                __marshalledValue_6670 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6671 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6670 = __notNullable_6671.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onspeechstart", __marshalledValue_6670);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onspeechend
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6672;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6673 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onspeechend");
            if (__res_6673 is null)
            {
                __res_6672 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6674 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6673;
                __res_6672 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6674);
            }
            return __res_6672;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6675;
            if (value is null)
            {
                __marshalledValue_6675 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6676 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6675 = __notNullable_6676.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onspeechend", __marshalledValue_6675);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onsoundend
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6677;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6678 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onsoundend");
            if (__res_6678 is null)
            {
                __res_6677 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6679 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6678;
                __res_6677 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6679);
            }
            return __res_6677;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6680;
            if (value is null)
            {
                __marshalledValue_6680 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6681 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6680 = __notNullable_6681.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onsoundend", __marshalledValue_6680);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onaudioend
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6682;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6683 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onaudioend");
            if (__res_6683 is null)
            {
                __res_6682 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6684 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6683;
                __res_6682 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6684);
            }
            return __res_6682;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6685;
            if (value is null)
            {
                __marshalledValue_6685 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6686 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6685 = __notNullable_6686.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onaudioend", __marshalledValue_6685);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onresult
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6687;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6688 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onresult");
            if (__res_6688 is null)
            {
                __res_6687 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6689 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6688;
                __res_6687 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6689);
            }
            return __res_6687;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6690;
            if (value is null)
            {
                __marshalledValue_6690 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6691 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6690 = __notNullable_6691.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onresult", __marshalledValue_6690);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onnomatch
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6692;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6693 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onnomatch");
            if (__res_6693 is null)
            {
                __res_6692 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6694 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6693;
                __res_6692 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6694);
            }
            return __res_6692;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6695;
            if (value is null)
            {
                __marshalledValue_6695 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6696 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6695 = __notNullable_6696.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onnomatch", __marshalledValue_6695);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onerror
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6697;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6698 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onerror");
            if (__res_6698 is null)
            {
                __res_6697 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6699 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6698;
                __res_6697 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6699);
            }
            return __res_6697;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6700;
            if (value is null)
            {
                __marshalledValue_6700 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6701 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6700 = __notNullable_6701.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onerror", __marshalledValue_6700);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onstart
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6702;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6703 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onstart");
            if (__res_6703 is null)
            {
                __res_6702 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6704 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6703;
                __res_6702 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6704);
            }
            return __res_6702;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6705;
            if (value is null)
            {
                __marshalledValue_6705 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6706 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6705 = __notNullable_6706.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onstart", __marshalledValue_6705);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onend
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_6707;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_6708 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onend");
            if (__res_6708 is null)
            {
                __res_6707 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_6709 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_6708;
                __res_6707 = new global::Iskra.StdWeb.EventHandlerNonNull(__notNullable_6709);
            }
            return __res_6707;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_6710;
            if (value is null)
            {
                __marshalledValue_6710 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_6711 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                __marshalledValue_6710 = __notNullable_6711.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onend", __marshalledValue_6710);
        }
    }
}

#nullable disable