// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class SVGAnimatedBoolean(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public bool BaseVal
    {
        get
        {
            bool __res_874;
            bool __res_875 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "baseVal");
            __res_874 = __res_875;
            return __res_874;
        }
        set
        {
            bool __marshalledValue_876;
            __marshalledValue_876 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "baseVal", __marshalledValue_876);
        }
    }

    public bool AnimVal
    {
        get
        {
            bool __res_877;
            bool __res_878 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "animVal");
            __res_877 = __res_878;
            return __res_877;
        }
    }
}

#nullable disable