// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class SVGFESpecularLightingElement(global::System.Runtime.InteropServices.JavaScript.JSObject obj): SVGElement(obj)
{
    public global::Iskra.StdWeb.SVGAnimatedString In1
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedString __res_2506;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2507 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "in1");
            __res_2506 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedString>(__res_2507);
            return __res_2506;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedNumber SurfaceScale
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedNumber __res_2508;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2509 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "surfaceScale");
            __res_2508 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedNumber>(__res_2509);
            return __res_2508;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedNumber SpecularConstant
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedNumber __res_2510;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2511 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "specularConstant");
            __res_2510 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedNumber>(__res_2511);
            return __res_2510;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedNumber SpecularExponent
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedNumber __res_2512;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2513 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "specularExponent");
            __res_2512 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedNumber>(__res_2513);
            return __res_2512;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedNumber KernelUnitLengthX
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedNumber __res_2514;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2515 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "kernelUnitLengthX");
            __res_2514 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedNumber>(__res_2515);
            return __res_2514;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedNumber KernelUnitLengthY
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedNumber __res_2516;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2517 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "kernelUnitLengthY");
            __res_2516 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedNumber>(__res_2517);
            return __res_2516;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedLength X
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedLength __res_2518;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2519 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "x");
            __res_2518 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedLength>(__res_2519);
            return __res_2518;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedLength Y
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedLength __res_2520;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2521 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "y");
            __res_2520 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedLength>(__res_2521);
            return __res_2520;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedLength Width
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedLength __res_2522;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2523 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "width");
            __res_2522 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedLength>(__res_2523);
            return __res_2522;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedLength Height
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedLength __res_2524;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2525 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "height");
            __res_2524 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedLength>(__res_2525);
            return __res_2524;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedString Result
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedString __res_2526;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2527 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "result");
            __res_2526 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedString>(__res_2527);
            return __res_2526;
        }
    }
}

#nullable disable