// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class SVGFEFuncBElement(global::System.Runtime.InteropServices.JavaScript.JSObject obj): SVGComponentTransferFunctionElement(obj)
{

}

#nullable disable