// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class SVGFEGaussianBlurElement(global::System.Runtime.InteropServices.JavaScript.JSObject obj): SVGElement(obj)
{
    public global::Iskra.StdWeb.SVGAnimatedString In1
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedString __res_1278;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_1279 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "in1");
            __res_1278 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedString>(__res_1279);
            return __res_1278;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedNumber StdDeviationX
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedNumber __res_1280;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_1281 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "stdDeviationX");
            __res_1280 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedNumber>(__res_1281);
            return __res_1280;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedNumber StdDeviationY
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedNumber __res_1282;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_1283 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "stdDeviationY");
            __res_1282 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedNumber>(__res_1283);
            return __res_1282;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedEnumeration EdgeMode
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedEnumeration __res_1284;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_1285 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "edgeMode");
            __res_1284 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedEnumeration>(__res_1285);
            return __res_1284;
        }
    }
}

#nullable disable