// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class SVGMaskElement(global::System.Runtime.InteropServices.JavaScript.JSObject obj): SVGElement(obj)
{
    public global::Iskra.StdWeb.SVGAnimatedEnumeration MaskUnits
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedEnumeration __res_4505;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_4506 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "maskUnits");
            __res_4505 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedEnumeration>(__res_4506);
            return __res_4505;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedEnumeration MaskContentUnits
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedEnumeration __res_4507;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_4508 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "maskContentUnits");
            __res_4507 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedEnumeration>(__res_4508);
            return __res_4507;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedLength X
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedLength __res_4509;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_4510 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "x");
            __res_4509 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedLength>(__res_4510);
            return __res_4509;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedLength Y
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedLength __res_4511;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_4512 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "y");
            __res_4511 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedLength>(__res_4512);
            return __res_4511;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedLength Width
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedLength __res_4513;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_4514 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "width");
            __res_4513 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedLength>(__res_4514);
            return __res_4513;
        }
    }

    public global::Iskra.StdWeb.SVGAnimatedLength Height
    {
        get
        {
            global::Iskra.StdWeb.SVGAnimatedLength __res_4515;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_4516 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "height");
            __res_4515 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.SVGAnimatedLength>(__res_4516);
            return __res_4515;
        }
    }
}

#nullable disable