// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class TextFormatUpdateEvent(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.StdWeb.Event(obj)
{
    public static global::Iskra.StdWeb.TextFormatUpdateEvent New(string type)
    {
        int ___argsArrayLength_0 = 1;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_3088 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        string ___marshalledValue_1;
        ___marshalledValue_1 = type;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(__argsArray_3088.JSObject, 0, ___marshalledValue_1);

        global::System.Runtime.InteropServices.JavaScript.JSObject __res_3090 = global::Iskra.JSCore.Extensions.JSConstructorExtensions.ConstructObjectNonEmpty(global::System.Runtime.InteropServices.JavaScript.JSHost.GlobalThis, "TextFormatUpdateEvent", __argsArray_3088.JSObject);
        return new global::Iskra.StdWeb.TextFormatUpdateEvent(__res_3090);
    }

    public static global::Iskra.StdWeb.TextFormatUpdateEvent New(string type, global::Iskra.StdWeb.TextFormatUpdateEventInit options)
    {
        int ___argsArrayLength_0 = 2;

        using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_3085 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(___argsArrayLength_0);

        // Argument 1
        string ___marshalledValue_1;
        ___marshalledValue_1 = type;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(__argsArray_3085.JSObject, 0, ___marshalledValue_1);

        // Argument 2
        global::System.Runtime.InteropServices.JavaScript.JSObject ___marshalledValue_2;
        ___marshalledValue_2 = options.JSObject;
        global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(__argsArray_3085.JSObject, 1, ___marshalledValue_2);

        global::System.Runtime.InteropServices.JavaScript.JSObject __res_3087 = global::Iskra.JSCore.Extensions.JSConstructorExtensions.ConstructObjectNonEmpty(global::System.Runtime.InteropServices.JavaScript.JSHost.GlobalThis, "TextFormatUpdateEvent", __argsArray_3085.JSObject);
        return new global::Iskra.StdWeb.TextFormatUpdateEvent(__res_3087);
    }

    public global::Iskra.JSCore.Generics.JSArray<global::Iskra.StdWeb.TextFormat, global::Iskra.StdWeb.PropertyAccessor> GetTextFormats()
    {
        using global::Iskra.JSCore.FunctionResPool.Owner ___resOwner_1 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

        global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallEmptyNonVoidFunctionProperty(JSObject, "getTextFormats", JSObject, ___resOwner_1.JSObject);

        // Return Value
        return global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.JSCore.Generics.JSArray<global::Iskra.StdWeb.TextFormat, global::Iskra.StdWeb.PropertyAccessor>, global::Iskra.StdWeb.PropertyAccessor>(___resOwner_1.JSObject, "value");
    }
}

#nullable disable