// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public delegate global::Iskra.JSCore.Promise UnderlyingSinkAbortCallbackManaged(global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>? reason);

public partial class UnderlyingSinkAbortCallback(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public static implicit operator UnderlyingSinkAbortCallback(UnderlyingSinkAbortCallbackManaged input)
    {
        Action<global::System.Runtime.InteropServices.JavaScript.JSObject, global::System.Runtime.InteropServices.JavaScript.JSObject> callback = (__args_385, __res_390) =>
        {
            using (__args_385)
            using (__res_390)
            {
                // Argument 1
                global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>? __arg_387;
                global::System.Runtime.InteropServices.JavaScript.JSObject? __propObject_388;
                __propObject_388 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsUnionV2AsNullable(__args_385, 0);
                if (__propObject_388 is null)
                {
                    __arg_387 = null;
                }
                else
                {
                    __arg_387 = new global::Iskra.JSCore.Generics.Union<double, global::System.Numerics.BigInteger, string, bool, global::System.Runtime.InteropServices.JavaScript.JSObject, object, global::Iskra.StdWeb.GenericMarshaller.Union>(__propObject_388);
                }

                global::Iskra.JSCore.Promise __managedRes_391 = input(__arg_387);

                global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_392 = __managedRes_391.JSObject;
                global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(__res_390, "value", __propObject_392);
            }
        };

        global::System.Runtime.InteropServices.JavaScript.JSObject __funcObj_389 = global::Iskra.JSCore.Extensions.JSFunctionExtensions.WrapAsNonVoidFunction(callback);
        global::Iskra.JSCore.Extensions.JSFunctionExtensions.StoreManagedFunctionToProperty(__funcObj_389, input); 

        return new global::Iskra.StdWeb.UnderlyingSinkAbortCallback(__funcObj_389);
    }

    public bool TryGetManaged([global::System.Diagnostics.CodeAnalysis.NotNullWhenAttribute(true)] out global::Iskra.StdWeb.UnderlyingSinkAbortCallbackManaged? managed, bool allowConversion = false)
    {
        managed = global::Iskra.JSCore.Extensions.JSFunctionExtensions.GetManagedFunctionFromProperty(JSObject) as global::Iskra.StdWeb.UnderlyingSinkAbortCallbackManaged;
        if (managed is not null)
        {
            return true;
        }

        if (!allowConversion)
        {
            return false;
        }

        managed = (reason) =>
        {
            int __argsArrayLength_396 = 1;

            using global::Iskra.JSCore.ArgsArrayPool.Owner __argsArray_393 = global::Iskra.JSCore.ArgsArrayPool.Shared.Rent(__argsArrayLength_396);

            // Argument 1
            global::System.Runtime.InteropServices.JavaScript.JSObject? __propObject_397;
            if (reason is null)
            {
                __propObject_397 = null;
            }
            else
            {
                __propObject_397 = reason.JSObject;
            }

            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsUnionAsNullable(__argsArray_393.JSObject, 0, __propObject_397);

            using global::Iskra.JSCore.FunctionResPool.Owner __resOwner_394 = global::Iskra.JSCore.FunctionResPool.Shared.Rent();

            global::Iskra.JSCore.Extensions.JSFunctionExtensions.CallNonEmptyNonVoidFunction(JSObject, null, __argsArray_393.JSObject, __resOwner_394.JSObject);

            // Return Value
            global::Iskra.JSCore.Promise __res_395;
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_398;
            __propObject_398 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(__resOwner_394.JSObject, "value");
            __res_395 = new global::Iskra.JSCore.Promise(__propObject_398);
            return __res_395;
        };
        return true;
    }
}

#nullable disable