// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class USBIsochronousOutTransferPacket(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public uint BytesWritten
    {
        get
        {
            uint __res_7648;
            double __res_7649 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "bytesWritten");
            __res_7648 = Convert.ToUInt32(__res_7649);
            return __res_7648;
        }
    }

    public global::Iskra.StdWeb.USBTransferStatus Status
    {
        get
        {
            global::Iskra.StdWeb.USBTransferStatus __res_7650;
            string __res_7651 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "status");
            __res_7650 = global::Iskra.StdWeb.USBTransferStatus.Create(__res_7651);
            return __res_7650;
        }
    }
}

#nullable disable