// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class USBPermissionResult(global::System.Runtime.InteropServices.JavaScript.JSObject obj): PermissionStatus(obj)
{
    public global::Iskra.JSCore.Generics.FrozenArray<global::Iskra.StdWeb.USBDevice, global::Iskra.StdWeb.GenericMarshaller.FrozenArray> Devices
    {
        get
        {
            global::Iskra.JSCore.Generics.FrozenArray<global::Iskra.StdWeb.USBDevice, global::Iskra.StdWeb.GenericMarshaller.FrozenArray> __res_5154;
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_5155;
            __propObject_5155 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "devices");
            __res_5154 = new global::Iskra.JSCore.Generics.FrozenArray<global::Iskra.StdWeb.USBDevice, global::Iskra.StdWeb.GenericMarshaller.FrozenArray>(__propObject_5155);
            return __res_5154;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_5156 = value.JSObject;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(JSObject, "devices", __propObject_5156);
        }
    }
}

#nullable disable