// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class ValidityState(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public bool ValueMissing
    {
        get
        {
            bool __res_6420;
            bool __res_6421 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "valueMissing");
            __res_6420 = __res_6421;
            return __res_6420;
        }
    }

    public bool TypeMismatch
    {
        get
        {
            bool __res_6422;
            bool __res_6423 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "typeMismatch");
            __res_6422 = __res_6423;
            return __res_6422;
        }
    }

    public bool PatternMismatch
    {
        get
        {
            bool __res_6424;
            bool __res_6425 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "patternMismatch");
            __res_6424 = __res_6425;
            return __res_6424;
        }
    }

    public bool TooLong
    {
        get
        {
            bool __res_6426;
            bool __res_6427 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "tooLong");
            __res_6426 = __res_6427;
            return __res_6426;
        }
    }

    public bool TooShort
    {
        get
        {
            bool __res_6428;
            bool __res_6429 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "tooShort");
            __res_6428 = __res_6429;
            return __res_6428;
        }
    }

    public bool RangeUnderflow
    {
        get
        {
            bool __res_6430;
            bool __res_6431 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "rangeUnderflow");
            __res_6430 = __res_6431;
            return __res_6430;
        }
    }

    public bool RangeOverflow
    {
        get
        {
            bool __res_6432;
            bool __res_6433 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "rangeOverflow");
            __res_6432 = __res_6433;
            return __res_6432;
        }
    }

    public bool StepMismatch
    {
        get
        {
            bool __res_6434;
            bool __res_6435 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "stepMismatch");
            __res_6434 = __res_6435;
            return __res_6434;
        }
    }

    public bool BadInput
    {
        get
        {
            bool __res_6436;
            bool __res_6437 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "badInput");
            __res_6436 = __res_6437;
            return __res_6436;
        }
    }

    public bool CustomError
    {
        get
        {
            bool __res_6438;
            bool __res_6439 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "customError");
            __res_6438 = __res_6439;
            return __res_6438;
        }
    }

    public bool Valid
    {
        get
        {
            bool __res_6440;
            bool __res_6441 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "valid");
            __res_6440 = __res_6441;
            return __res_6440;
        }
    }
}

#nullable disable