// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class VideoTrackGenerator(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public global::Iskra.StdWeb.WritableStream Writable
    {
        get
        {
            global::Iskra.StdWeb.WritableStream __res_288;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_289 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "writable");
            __res_288 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.WritableStream>(__res_289);
            return __res_288;
        }
    }

    public bool Muted
    {
        get
        {
            bool __res_290;
            bool __res_291 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "muted");
            __res_290 = __res_291;
            return __res_290;
        }
        set
        {
            bool __marshalledValue_292;
            __marshalledValue_292 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "muted", __marshalledValue_292);
        }
    }

    public global::Iskra.StdWeb.MediaStreamTrack Track
    {
        get
        {
            global::Iskra.StdWeb.MediaStreamTrack __res_293;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_294 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "track");
            __res_293 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.MediaStreamTrack>(__res_294);
            return __res_293;
        }
    }
}

#nullable disable