// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class VideoEncoder(JSObject obj): EventTarget(obj)
{
    public Iskra.StdWeb.CodecState State
    {
        get
        {
            Iskra.StdWeb.CodecState __res_1050;
            throw new Exception();
            return __res_1050;
        }
    }

    public uint EncodeQueueSize
    {
        get
        {
            uint __res_1051;
            throw new Exception();
            return __res_1051;
        }
    }

    public Iskra.StdWeb.EventHandlerNonNull? Ondequeue
    {
        get
        {
            Iskra.StdWeb.EventHandlerNonNull? __res_1052;
            throw new Exception();
            return __res_1052;
        }
        set
        {
            throw new Exception();
        }
    }
}

#nullable disable