// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class VTTCue(global::System.Runtime.InteropServices.JavaScript.JSObject obj): TextTrackCue(obj)
{
    public global::Iskra.StdWeb.VTTRegion? Region
    {
        get
        {
            global::Iskra.StdWeb.VTTRegion? __res_12920;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_12921 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "region");
            if (__res_12921 is null)
            {
                __res_12920 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_12922 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_12921;
                __res_12920 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.VTTRegion>(__notNullable_12922);
            }
            return __res_12920;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_12923;
            if (value is null)
            {
                __marshalledValue_12923 = null;
            }
            else
            {
                global::Iskra.StdWeb.VTTRegion __notNullable_12924 = (global::Iskra.StdWeb.VTTRegion)value;
                __marshalledValue_12923 = __notNullable_12924.JSObject;
            }
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "region", __marshalledValue_12923);
        }
    }

    public global::Iskra.StdWeb.DirectionSetting Vertical
    {
        get
        {
            global::Iskra.StdWeb.DirectionSetting __res_12925;
            string __res_12926 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "vertical");
            __res_12925 = global::Iskra.StdWeb.DirectionSetting.Create(__res_12926);
            return __res_12925;
        }
        set
        {
            string __marshalledValue_12927;
            __marshalledValue_12927 = value.ToString();
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "vertical", __marshalledValue_12927);
        }
    }

    public bool SnapToLines
    {
        get
        {
            bool __res_12928;
            bool __res_12929 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "snapToLines");
            __res_12928 = __res_12929;
            return __res_12928;
        }
        set
        {
            bool __marshalledValue_12930;
            __marshalledValue_12930 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsBooleanV2(JSObject, "snapToLines", __marshalledValue_12930);
        }
    }

    public global::Iskra.JSCore.Generics.Union<double, global::Iskra.StdWeb.AutoKeyword, global::Iskra.StdWeb.GenericMarshaller.Union> Line
    {
        get
        {
            global::Iskra.JSCore.Generics.Union<double, global::Iskra.StdWeb.AutoKeyword, global::Iskra.StdWeb.GenericMarshaller.Union> __res_12931;
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_12932;
            __propObject_12932 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsUnionV2(JSObject, "line");
            __res_12931 = new global::Iskra.JSCore.Generics.Union<double, global::Iskra.StdWeb.AutoKeyword, global::Iskra.StdWeb.GenericMarshaller.Union>(__propObject_12932);
            return __res_12931;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_12933 = value.JSObject;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsUnion(JSObject, "line", __propObject_12933);
        }
    }

    public global::Iskra.StdWeb.LineAlignSetting LineAlign
    {
        get
        {
            global::Iskra.StdWeb.LineAlignSetting __res_12934;
            string __res_12935 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "lineAlign");
            __res_12934 = global::Iskra.StdWeb.LineAlignSetting.Create(__res_12935);
            return __res_12934;
        }
        set
        {
            string __marshalledValue_12936;
            __marshalledValue_12936 = value.ToString();
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "lineAlign", __marshalledValue_12936);
        }
    }

    public global::Iskra.JSCore.Generics.Union<double, global::Iskra.StdWeb.AutoKeyword, global::Iskra.StdWeb.GenericMarshaller.Union> Position
    {
        get
        {
            global::Iskra.JSCore.Generics.Union<double, global::Iskra.StdWeb.AutoKeyword, global::Iskra.StdWeb.GenericMarshaller.Union> __res_12937;
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_12938;
            __propObject_12938 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsUnionV2(JSObject, "position");
            __res_12937 = new global::Iskra.JSCore.Generics.Union<double, global::Iskra.StdWeb.AutoKeyword, global::Iskra.StdWeb.GenericMarshaller.Union>(__propObject_12938);
            return __res_12937;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject __propObject_12939 = value.JSObject;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsUnion(JSObject, "position", __propObject_12939);
        }
    }

    public global::Iskra.StdWeb.PositionAlignSetting PositionAlign
    {
        get
        {
            global::Iskra.StdWeb.PositionAlignSetting __res_12940;
            string __res_12941 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "positionAlign");
            __res_12940 = global::Iskra.StdWeb.PositionAlignSetting.Create(__res_12941);
            return __res_12940;
        }
        set
        {
            string __marshalledValue_12942;
            __marshalledValue_12942 = value.ToString();
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "positionAlign", __marshalledValue_12942);
        }
    }

    public double Size
    {
        get
        {
            double __res_12943;
            double __res_12944 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsDoubleV2(JSObject, "size");
            __res_12943 = __res_12944;
            return __res_12943;
        }
        set
        {
            double __marshalledValue_12945;
            __marshalledValue_12945 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsDoubleV2(JSObject, "size", __marshalledValue_12945);
        }
    }

    public global::Iskra.StdWeb.AlignSetting Align
    {
        get
        {
            global::Iskra.StdWeb.AlignSetting __res_12946;
            string __res_12947 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "align");
            __res_12946 = global::Iskra.StdWeb.AlignSetting.Create(__res_12947);
            return __res_12946;
        }
        set
        {
            string __marshalledValue_12948;
            __marshalledValue_12948 = value.ToString();
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "align", __marshalledValue_12948);
        }
    }

    public string Text
    {
        get
        {
            string __res_12949;
            string __res_12950 = global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsStringV2(JSObject, "text");
            __res_12949 = __res_12950;
            return __res_12949;
        }
        set
        {
            string __marshalledValue_12951;
            __marshalledValue_12951 = value;
            global::Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsStringV2(JSObject, "text", __marshalledValue_12951);
        }
    }
}

#nullable disable