// <auto-generated/>

using System.Runtime.InteropServices.JavaScript;
using Iskra.JSCore;

namespace Iskra.StdWeb;

#nullable enable

public partial class WebGLActiveInfo(JSObject obj): JSObjectProxy(obj)
{
    public GLint Size
    {
        get
        {
            throw new Exception();
        }
    }

    public GLenum Type
    {
        get
        {
            throw new Exception();
        }
    }

    public string Name
    {
        get
        {
            throw new Exception();
        }
    }
}

#nullable disable