// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class WindowClient(global::System.Runtime.InteropServices.JavaScript.JSObject obj): Client(obj)
{
    public global::Iskra.StdWeb.DocumentVisibilityState VisibilityState
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.DocumentVisibilityState, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "visibilityState");
    }

    public bool Focused
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<bool, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "focused");
    }

    public global::Iskra.JSCore.Generics.FrozenArray<string, global::Iskra.StdWeb.PropertyAccessor> AncestorOrigins
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.JSCore.Generics.FrozenArray<string, global::Iskra.StdWeb.PropertyAccessor>, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "ancestorOrigins");
    }

    public global::Iskra.JSCore.Generics.Promise<global::Iskra.StdWeb.WindowClient, global::Iskra.StdWeb.PropertyAccessor> Focus()
    {
        throw new global::System.Exception();
    }

    public global::Iskra.JSCore.Generics.Promise<global::Iskra.StdWeb.WindowClient?, global::Iskra.StdWeb.PropertyAccessorNullable> Navigate(string url)
    {
        throw new global::System.Exception();
    }
}

#nullable disable