// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class WorkerOptions(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{

}

#nullable disable