// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class XRCubeLayer(global::System.Runtime.InteropServices.JavaScript.JSObject obj): XRCompositionLayer(obj)
{
    public global::Iskra.StdWeb.XRSpace Space
    {
        get
        {
            global::Iskra.StdWeb.XRSpace __res_2683;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2684 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "space");
            __res_2683 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.XRSpace>(__res_2684);
            return __res_2683;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject __marshalledValue_2685;
            __marshalledValue_2685 = value.JSObject;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(JSObject, "space", __marshalledValue_2685);
        }
    }

    public global::Iskra.StdWeb.DOMPointReadOnly Orientation
    {
        get
        {
            global::Iskra.StdWeb.DOMPointReadOnly __res_2686;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_2687 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "orientation");
            __res_2686 = global::Iskra.JSCore.JSObjectProxyFactory.GetProxy<global::Iskra.StdWeb.DOMPointReadOnly>(__res_2687);
            return __res_2686;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject __marshalledValue_2688;
            __marshalledValue_2688 = value.JSObject;
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2(JSObject, "orientation", __marshalledValue_2688);
        }
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onredraw
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_2689;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_2690 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onredraw");
            if (__res_2690 is null)
            {
                __res_2689 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_2691 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_2690;
                throw new global::System.Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } not supported.");
            }
            return __res_2689;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_2692;
            if (value is null)
            {
                __marshalledValue_2692 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_2693 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                throw new global::System.Exception("Marshaller ToJS from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } not supported.");
            }
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onredraw", __marshalledValue_2692);
        }
    }
}

#nullable disable