// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class XRPose(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public global::Iskra.StdWeb.XRRigidTransform Transform
    {
        get
        {
            global::Iskra.StdWeb.XRRigidTransform __res_4303;
            global::System.Runtime.InteropServices.JavaScript.JSObject __res_4304 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2(JSObject, "transform");
            throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = XRRigidTransform } not supported.");
            return __res_4303;
        }
    }

    public global::Iskra.StdWeb.DOMPointReadOnly? LinearVelocity
    {
        get
        {
            global::Iskra.StdWeb.DOMPointReadOnly? __res_4305;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_4306 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "linearVelocity");
            if (__res_4306 is null)
            {
                __res_4305 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_4307 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_4306;
                throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = DOMPointReadOnly } not supported.");
            }
            return __res_4305;
        }
    }

    public global::Iskra.StdWeb.DOMPointReadOnly? AngularVelocity
    {
        get
        {
            global::Iskra.StdWeb.DOMPointReadOnly? __res_4308;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_4309 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "angularVelocity");
            if (__res_4309 is null)
            {
                __res_4308 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_4310 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_4309;
                throw new Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = DOMPointReadOnly } not supported.");
            }
            return __res_4308;
        }
    }

    public bool EmulatedPosition
    {
        get
        {
            bool __res_4311;
            bool __res_4312 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsBooleanV2(JSObject, "emulatedPosition");
            __res_4311 = __res_4312;
            return __res_4311;
        }
    }
}

#nullable disable