// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class XRReferenceSpace(global::System.Runtime.InteropServices.JavaScript.JSObject obj): XRSpace(obj)
{
    public global::Iskra.StdWeb.EventHandlerNonNull? Onreset
    {
        get
        {
            global::Iskra.StdWeb.EventHandlerNonNull? __res_4284;
            global::System.Runtime.InteropServices.JavaScript.JSObject? __res_4285 = Iskra.JSCore.Extensions.JSObjectPropertyExtensions.GetPropertyAsJSObjectV2AsNullable(JSObject, "onreset");
            if (__res_4285 is null)
            {
                __res_4284 = null;
            }
            else
            {
                global::System.Runtime.InteropServices.JavaScript.JSObject __notNullable_4286 = (global::System.Runtime.InteropServices.JavaScript.JSObject)__res_4285;
                throw new global::System.Exception("Marshaller ToManaged from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } not supported.");
            }
            return __res_4284;
        }
        set
        {
            global::System.Runtime.InteropServices.JavaScript.JSObject? __marshalledValue_4287;
            if (value is null)
            {
                __marshalledValue_4287 = null;
            }
            else
            {
                global::Iskra.StdWeb.EventHandlerNonNull __notNullable_4288 = (global::Iskra.StdWeb.EventHandlerNonNull)value;
                throw new global::System.Exception("Marshaller ToJS from SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = EventHandlerNonNull } to SingleTypeDescription { ExtAttrs = System.Collections.Generic.List`1[Iskra.WebIDLGenerator.Models.ExtendedAttribute], Nullable = False, IdlType = object } not supported.");
            }
            Iskra.JSCore.Extensions.JSObjectPropertyExtensions.SetPropertyAsJSObjectV2AsNullable(JSObject, "onreset", __marshalledValue_4287);
        }
    }
}

#nullable disable