// <auto-generated/>

namespace Iskra.StdWeb;

#nullable enable

public partial class XRSession(global::System.Runtime.InteropServices.JavaScript.JSObject obj): global::Iskra.JSCore.JSObjectProxy(obj)
{
    public global::Iskra.JSCore.Promise InitiateRoomCapture()
    {
        throw new global::System.Exception();
    }

    public global::Iskra.StdWeb.XREnvironmentBlendMode EnvironmentBlendMode
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.XREnvironmentBlendMode, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "environmentBlendMode");
    }

    public global::Iskra.StdWeb.XRInteractionMode InteractionMode
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.XRInteractionMode, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "interactionMode");
    }

    public global::Iskra.JSCore.Generics.Promise<global::Iskra.StdWeb.XRLightProbe, global::Iskra.StdWeb.PropertyAccessor> RequestLightProbe(global::Iskra.StdWeb.XRLightProbeInit options)
    {
        throw new global::System.Exception();
    }

    public global::Iskra.StdWeb.XRReflectionFormat PreferredReflectionFormat
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.XRReflectionFormat, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "preferredReflectionFormat");
    }

    public global::Iskra.JSCore.Generics.FrozenArray<string, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement> PersistentAnchors
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.JSCore.Generics.FrozenArray<string, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement>, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "persistentAnchors");
    }

    public global::Iskra.JSCore.Generics.Promise<global::Iskra.StdWeb.XRAnchor, global::Iskra.StdWeb.PropertyAccessor> RestorePersistentAnchor(string uuid)
    {
        throw new global::System.Exception();
    }

    public global::Iskra.JSCore.Promise DeletePersistentAnchor(string uuid)
    {
        throw new global::System.Exception();
    }

    public global::Iskra.StdWeb.XRDepthUsage DepthUsage
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.XRDepthUsage, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "depthUsage");
    }

    public global::Iskra.StdWeb.XRDepthDataFormat DepthDataFormat
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.XRDepthDataFormat, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "depthDataFormat");
    }

    public global::Iskra.StdWeb.XRDepthType? DepthType
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.XRDepthType?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "depthType");
    }

    public bool? DepthActive
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<bool?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "depthActive");
    }

    public void PauseDepthSensing()
    {
        throw new global::System.Exception();
    }

    public void ResumeDepthSensing()
    {
        throw new global::System.Exception();
    }

    public global::Iskra.StdWeb.XRVisibilityState VisibilityState
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.XRVisibilityState, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "visibilityState");
    }

    public float? FrameRate
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<float?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "frameRate");
    }

    public global::Iskra.JSCore.Float32Array? SupportedFrameRates
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.JSCore.Float32Array?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "supportedFrameRates");
    }

    public global::Iskra.StdWeb.XRRenderState RenderState
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.XRRenderState, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "renderState");
    }

    public global::Iskra.StdWeb.XRInputSourceArray InputSources
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.XRInputSourceArray, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "inputSources");
    }

    public global::Iskra.StdWeb.XRInputSourceArray TrackedSources
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.XRInputSourceArray, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "trackedSources");
    }

    public global::Iskra.JSCore.Generics.FrozenArray<string, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement> EnabledFeatures
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.JSCore.Generics.FrozenArray<string, global::Iskra.StdWeb.GenericMarshaller.ArrayLikeElement>, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "enabledFeatures");
    }

    public bool IsSystemKeyboardSupported
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<bool, global::Iskra.StdWeb.PropertyAccessor>(JSObject, "isSystemKeyboardSupported");
    }

    public void UpdateRenderState(global::Iskra.StdWeb.XRRenderStateInit state)
    {
        throw new global::System.Exception();
    }

    public global::Iskra.JSCore.Promise UpdateTargetFrameRate(float rate)
    {
        throw new global::System.Exception();
    }

    public global::Iskra.JSCore.Generics.Promise<global::Iskra.StdWeb.XRReferenceSpace, global::Iskra.StdWeb.PropertyAccessor> RequestReferenceSpace(global::Iskra.StdWeb.XRReferenceSpaceType type)
    {
        throw new global::System.Exception();
    }

    public uint RequestAnimationFrame(global::Iskra.StdWeb.XRFrameRequestCallback callback)
    {
        throw new global::System.Exception();
    }

    public void CancelAnimationFrame(uint handle)
    {
        throw new global::System.Exception();
    }

    public global::Iskra.JSCore.Promise End()
    {
        throw new global::System.Exception();
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onend
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onend");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onend", value);
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Oninputsourceschange
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "oninputsourceschange");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "oninputsourceschange", value);
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onselect
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onselect");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onselect", value);
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onselectstart
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onselectstart");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onselectstart", value);
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onselectend
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onselectend");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onselectend", value);
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onsqueeze
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onsqueeze");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onsqueeze", value);
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onsqueezestart
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onsqueezestart");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onsqueezestart", value);
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onsqueezeend
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onsqueezeend");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onsqueezeend", value);
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onvisibilitychange
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onvisibilitychange");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onvisibilitychange", value);
    }

    public global::Iskra.StdWeb.EventHandlerNonNull? Onframeratechange
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onframeratechange");
        set => global::Iskra.JSCore.Generics.PropertyAccessor.Set<global::Iskra.StdWeb.EventHandlerNonNull?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "onframeratechange", value);
    }

    public global::Iskra.JSCore.Generics.Promise<global::Iskra.StdWeb.XRHitTestSource, global::Iskra.StdWeb.PropertyAccessor> RequestHitTestSource(global::Iskra.StdWeb.XRHitTestOptionsInit options)
    {
        throw new global::System.Exception();
    }

    public global::Iskra.JSCore.Generics.Promise<global::Iskra.StdWeb.XRTransientInputHitTestSource, global::Iskra.StdWeb.PropertyAccessor> RequestHitTestSourceForTransientInput(global::Iskra.StdWeb.XRTransientInputHitTestOptionsInit options)
    {
        throw new global::System.Exception();
    }

    public global::Iskra.StdWeb.XRDOMOverlayState? DomOverlayState
    {
        get => global::Iskra.JSCore.Generics.PropertyAccessor.Get<global::Iskra.StdWeb.XRDOMOverlayState?, global::Iskra.StdWeb.PropertyAccessorNullable>(JSObject, "domOverlayState");
    }
}

#nullable disable