//HintName: GeneratedStaticAssetPathsAttribute.g.cs
// <auto-generated/>
#nullable enable

namespace Iskra.Core;

[System.AttributeUsage(System.AttributeTargets.Class)]
public sealed class GeneratedStaticAssetPathsAttribute : System.Attribute { }